/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface F1040Sc {
  f1_1_0?: string;
  f1_2_0?: string;
  f1_3_0?: string;
  f1_4_0?: string;
  f1_5_0?: string;
  f1_6_0?: string;
  f1_7_0?: string;
  f1_8_0?: string;
  c1_1_0?: boolean;
  c1_1_1?: boolean;
  c1_1_2?: boolean;
  f1_9_0?: string;
  c1_2_0?: boolean;
  c1_2_1?: boolean;
  c1_3_0?: boolean;
  c1_4_0?: boolean;
  c1_4_1?: boolean;
  c1_5_0?: boolean;
  c1_5_1?: boolean;
  c1_6_0?: boolean;
  f1_10_0?: string;
  f1_11_0?: string;
  f1_12_0?: string;
  f1_13_0?: string;
  f1_14_0?: string;
  f1_15_0?: string;
  f1_16_0?: string;
  f1_17_0?: string;
  f1_18_0?: string;
  f1_19_0?: string;
  f1_20_0?: string;
  f1_21_0?: string;
  f1_22_0?: string;
  f1_23_0?: string;
  f1_24_0?: string;
  f1_25_0?: string;
  f1_26_0?: string;
  f1_27_0?: string;
  f1_28_0?: string;
  f1_29_0?: string;
  f1_30_0?: string;
  f1_31_0?: string;
  f1_32_0?: string;
  f1_33_0?: string;
  f1_34_0?: string;
  f1_35_0?: string;
  f1_36_0?: string;
  f1_37_0?: string;
  f1_38_0?: string;
  f1_39_0?: string;
  f1_40_0?: string;
  f1_41_0?: string;
  f1_42_0?: string;
  f1_43_0?: string;
  f1_44_0?: string;
  f1_45_0?: string;
  f1_46_0?: string;
  c1_7_0?: boolean;
  c1_7_1?: boolean;
  c2_1_0?: boolean;
  c2_2_0?: boolean;
  c2_3_0?: boolean;
  c2_4_0?: boolean;
  c2_4_1?: boolean;
  f2_1_0?: string;
  f2_2_0?: string;
  f2_3_0?: string;
  f2_4_0?: string;
  f2_5_0?: string;
  f2_6_0?: string;
  f2_7_0?: string;
  f2_8_0?: string;
  f2_9_0?: string;
  f2_10_0?: string;
  f2_11_0?: string;
  f2_12_0?: string;
  f2_13_0?: string;
  f2_14_0?: string;
  c2_5_0?: boolean;
  c2_5_1?: boolean;
  c2_6_0?: boolean;
  c2_6_1?: boolean;
  c2_7_0?: boolean;
  c2_7_1?: boolean;
  c2_8_0?: boolean;
  c2_8_1?: boolean;
  f2_15_0?: string;
  f2_16_0?: string;
  f2_17_0?: string;
  f2_18_0?: string;
  f2_19_0?: string;
  f2_20_0?: string;
  f2_21_0?: string;
  f2_22_0?: string;
  f2_23_0?: string;
  f2_24_0?: string;
  f2_25_0?: string;
  f2_26_0?: string;
  f2_27_0?: string;
  f2_28_0?: string;
  f2_29_0?: string;
  f2_30_0?: string;
  f2_31_0?: string;
  f2_32_0?: string;
  f2_33_0?: string;
}


export const f1040sc = [
  {
    "nickname": "Name",
    "fieldName": "topmostSubform[0].Page1[0].f1_1[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SSN",
    "fieldName": "topmostSubform[0].Page1[0].f1_2[0]",
    "fieldType": "String"
  },
  {
    "nickname": "LA",
    "fieldName": "topmostSubform[0].Page1[0].f1_3[0]",
    "fieldType": "String"
  },
  {
    "nickname": "LB",
    "fieldName": "topmostSubform[0].Page1[0].BComb[0].f1_4[0]",
    "fieldType": "String"
  },
  {
    "nickname": "LC",
    "fieldName": "topmostSubform[0].Page1[0].f1_5[0]",
    "fieldType": "String"
  },
  {
    "nickname": "LD",
    "fieldName": "topmostSubform[0].Page1[0].DComb[0].f1_6[0]",
    "fieldType": "String"
  },
  {
    "nickname": "LER1",
    "fieldName": "topmostSubform[0].Page1[0].f1_7[0]",
    "fieldType": "String"
  },
  {
    "nickname": "LER2",
    "fieldName": "topmostSubform[0].Page1[0].f1_8[0]",
    "fieldType": "String"
  },
  {
    "nickname": "CF_Cash",
    "fieldName": "topmostSubform[0].Page1[0].c1_1[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "CF_Accrual",
    "fieldName": "topmostSubform[0].Page1[0].c1_1[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "CF_Other",
    "fieldName": "topmostSubform[0].Page1[0].c1_1[2]",
    "fieldType": "Boolean",
    "checkmark": "3"
  },
  {
    "nickname": "LF",
    "fieldName": "topmostSubform[0].Page1[0].f1_9[0]",
    "fieldType": "String"
  },
  {
    "nickname": "CG_Yes",
    "fieldName": "topmostSubform[0].Page1[0].c1_2[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  },
  {
    "nickname": "CG_No",
    "fieldName": "topmostSubform[0].Page1[0].c1_2[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "CH",
    "fieldName": "topmostSubform[0].Page1[0].c1_3[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "CI_Yes",
    "fieldName": "topmostSubform[0].Page1[0].c1_4[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  },
  {
    "nickname": "CI_No",
    "fieldName": "topmostSubform[0].Page1[0].c1_4[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "CJ_Yes",
    "fieldName": "topmostSubform[0].Page1[0].c1_5[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  },
  {
    "nickname": "CJ_No",
    "fieldName": "topmostSubform[0].Page1[0].c1_5[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "C1",
    "fieldName": "topmostSubform[0].Page1[0].c1_6[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L1",
    "fieldName": "topmostSubform[0].Page1[0].f1_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L2",
    "fieldName": "topmostSubform[0].Page1[0].f1_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L3",
    "fieldName": "topmostSubform[0].Page1[0].f1_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L4",
    "fieldName": "topmostSubform[0].Page1[0].f1_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5",
    "fieldName": "topmostSubform[0].Page1[0].f1_14[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L6",
    "fieldName": "topmostSubform[0].Page1[0].f1_15[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L7",
    "fieldName": "topmostSubform[0].Page1[0].f1_16[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_17[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L9",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_18[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L10",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_19[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L11",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L12",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_21[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L13",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_22[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_23[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L15",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_24[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L16a",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_25[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L16b",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_26[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L17",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_27[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_28[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L19",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_29[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L20a",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_30[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L20b",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_31[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L21",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_32[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_33[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L23",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_34[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L24a",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_35[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L24b",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_36[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L25",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_37[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L26",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_38[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L27a",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_39[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L27b",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_40[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L28",
    "fieldName": "topmostSubform[0].Page1[0].f1_41[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L29",
    "fieldName": "topmostSubform[0].Page1[0].f1_42[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L30a",
    "fieldName": "topmostSubform[0].Page1[0].f1_43[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L30b",
    "fieldName": "topmostSubform[0].Page1[0].f1_44[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L30",
    "fieldName": "topmostSubform[0].Page1[0].f1_45[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L31",
    "fieldName": "topmostSubform[0].Page1[0].f1_46[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C32a",
    "fieldName": "topmostSubform[0].Page1[0].c1_7[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C32b",
    "fieldName": "topmostSubform[0].Page1[0].c1_7[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "C33a",
    "fieldName": "topmostSubform[0].Page2[0].c2_1[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C33b",
    "fieldName": "topmostSubform[0].Page2[0].c2_2[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C33c",
    "fieldName": "topmostSubform[0].Page2[0].c2_3[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C34a",
    "fieldName": "topmostSubform[0].Page2[0].c2_4[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  },
  {
    "nickname": "C34b",
    "fieldName": "topmostSubform[0].Page2[0].c2_4[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "L35",
    "fieldName": "topmostSubform[0].Page2[0].f2_1[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L36",
    "fieldName": "topmostSubform[0].Page2[0].f2_2[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L37",
    "fieldName": "topmostSubform[0].Page2[0].f2_3[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L38",
    "fieldName": "topmostSubform[0].Page2[0].f2_4[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L39",
    "fieldName": "topmostSubform[0].Page2[0].f2_5[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L40",
    "fieldName": "topmostSubform[0].Page2[0].f2_6[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L41",
    "fieldName": "topmostSubform[0].Page2[0].f2_7[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L42",
    "fieldName": "topmostSubform[0].Page2[0].f2_8[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L43_MM",
    "fieldName": "topmostSubform[0].Page2[0].f2_9[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L43_DD",
    "fieldName": "topmostSubform[0].Page2[0].f2_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L43_YY",
    "fieldName": "topmostSubform[0].Page2[0].f2_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L44a",
    "fieldName": "topmostSubform[0].Page2[0].f2_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L44b",
    "fieldName": "topmostSubform[0].Page2[0].f2_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L44c",
    "fieldName": "topmostSubform[0].Page2[0].f2_14[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C45_Yes",
    "fieldName": "topmostSubform[0].Page2[0].c2_5[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  },
  {
    "nickname": "C45_No",
    "fieldName": "topmostSubform[0].Page2[0].c2_5[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "C46_Yes",
    "fieldName": "topmostSubform[0].Page2[0].c2_6[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  },
  {
    "nickname": "C46_No",
    "fieldName": "topmostSubform[0].Page2[0].c2_6[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "C47a_Yes",
    "fieldName": "topmostSubform[0].Page2[0].c2_7[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  },
  {
    "nickname": "C47a_No",
    "fieldName": "topmostSubform[0].Page2[0].c2_7[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "C47b_Yes",
    "fieldName": "topmostSubform[0].Page2[0].c2_8[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  },
  {
    "nickname": "C47b_No",
    "fieldName": "topmostSubform[0].Page2[0].c2_8[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "L48R1_desc",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item1[0].f2_15[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R1_amt",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item1[0].f2_16[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R2_desc",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item2[0].f2_17[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R2_amt",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item2[0].f2_18[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R3_desc",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item3[0].f2_19[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R3_amt",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item3[0].f2_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R4_desc",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item4[0].f2_21[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R4_amt",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item4[0].f2_22[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R5_desc",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item5[0].f2_23[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R5_amt",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item5[0].f2_24[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R6_desc",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item6[0].f2_25[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R6_amt",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item6[0].f2_26[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R7_desc",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item7[0].f2_27[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R7_amt",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item7[0].f2_28[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R8_desc",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item8[0].f2_29[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R8_amt",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item8[0].f2_30[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R9_desc",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item9[0].f2_31[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R9_amt",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item9[0].f2_32[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48",
    "fieldName": "topmostSubform[0].Page2[0].f2_33[0]",
    "fieldType": "String"
  }
];
