/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface F1040S2 {
  f1_01_0?: string;
  f1_02_0?: string;
  f1_03_0?: string;
  f1_04_0?: string;
  f1_05_0?: string;
  f1_06_0?: string;
  c1_1_0?: boolean;
  c1_2_0?: boolean;
  f1_07_0?: string;
  f1_08_0?: string;
  f1_09_0?: string;
  f1_10_0?: string;
  c1_3_0?: boolean;
  c1_4_0?: boolean;
  c1_5_0?: boolean;
  f1_11_0?: string;
  f1_12_0?: string;
  f1_13_0?: string;
  f1_14_0?: string;
}


export const f1040s2 = [
  {
    "nickname": "Name",
    "fieldName": "form1[0].Page1[0].f1_01[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SSN",
    "fieldName": "form1[0].Page1[0].f1_02[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1",
    "fieldName": "form1[0].Page1[0].f1_03[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L2",
    "fieldName": "form1[0].Page1[0].f1_04[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L3",
    "fieldName": "form1[0].Page1[0].f1_05[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L4",
    "fieldName": "form1[0].Page1[0].f1_06[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C5a",
    "fieldName": "form1[0].Page1[0].c1_1[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C5b",
    "fieldName": "form1[0].Page1[0].c1_2[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L5",
    "fieldName": "form1[0].Page1[0].f1_07[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L6",
    "fieldName": "form1[0].Page1[0].f1_08[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L7a",
    "fieldName": "form1[0].Page1[0].f1_09[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L7b",
    "fieldName": "form1[0].Page1[0].f1_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C8a",
    "fieldName": "form1[0].Page1[0].Line8[0].c1_3[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C8b",
    "fieldName": "form1[0].Page1[0].Line8[0].c1_4[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C8c",
    "fieldName": "form1[0].Page1[0].Line8[0].c1_5[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L8c",
    "fieldName": "form1[0].Page1[0].Line8[0].f1_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8",
    "fieldName": "form1[0].Page1[0].f1_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L9",
    "fieldName": "form1[0].Page1[0].f1_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L10",
    "fieldName": "form1[0].Page1[0].f1_14[0]",
    "fieldType": "String"
  }
];
