// This file was automatically generated by taxes/src/mappings/builder.ts

export interface F1040SC {
  Name?: string;
  SSN?: string;
  LA?: string;
  LB?: string;
  LC?: string;
  LD?: string;
  LER1?: string;
  LER2?: string;
  CF_Cash?: boolean;
  CF_Accrual?: boolean;
  CF_Other?: boolean;
  LF?: string;
  CG_Yes?: boolean;
  CG_No?: boolean;
  CH?: boolean;
  CI_Yes?: boolean;
  CI_No?: boolean;
  CJ_Yes?: boolean;
  CJ_No?: boolean;
  C1?: boolean;
  L1?: string;
  L2?: string;
  L3?: string;
  L4?: string;
  L5?: string;
  L6?: string;
  L7?: string;
  L8?: string;
  L9?: string;
  L10?: string;
  L11?: string;
  L12?: string;
  L13?: string;
  L14?: string;
  L15?: string;
  L16a?: string;
  L16b?: string;
  L17?: string;
  L18?: string;
  L19?: string;
  L20a?: string;
  L20b?: string;
  L21?: string;
  L22?: string;
  L23?: string;
  L24a?: string;
  L24b?: string;
  L25?: string;
  L26?: string;
  L27a?: string;
  L27b?: string;
  L28?: string;
  L29?: string;
  L30a?: string;
  L30b?: string;
  L30?: string;
  L31?: string;
  C32a?: boolean;
  C32b?: boolean;
  C33a?: boolean;
  C33b?: boolean;
  C33c?: boolean;
  C34a?: boolean;
  C34b?: boolean;
  L35?: string;
  L36?: string;
  L37?: string;
  L38?: string;
  L39?: string;
  L40?: string;
  L41?: string;
  L42?: string;
  L43_MM?: string;
  L43_DD?: string;
  L43_YY?: string;
  L44a?: string;
  L44b?: string;
  L44c?: string;
  C45_Yes?: boolean;
  C45_No?: boolean;
  C46_Yes?: boolean;
  C46_No?: boolean;
  C47a_Yes?: boolean;
  C47a_No?: boolean;
  C47b_Yes?: boolean;
  C47b_No?: boolean;
  L48R1_desc?: string;
  L48R1_amt?: string;
  L48R2_desc?: string;
  L48R2_amt?: string;
  L48R3_desc?: string;
  L48R3_amt?: string;
  L48R4_desc?: string;
  L48R4_amt?: string;
  L48R5_desc?: string;
  L48R5_amt?: string;
  L48R6_desc?: string;
  L48R6_amt?: string;
  L48R7_desc?: string;
  L48R7_amt?: string;
  L48R8_desc?: string;
  L48R8_amt?: string;
  L48R9_desc?: string;
  L48R9_amt?: string;
  L48?: string;
}

export const f1040sc = [
  {
    "nickname": "Name",
    "fieldName": "topmostSubform[0].Page1[0].f1_1[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SSN",
    "fieldName": "topmostSubform[0].Page1[0].f1_2[0]",
    "fieldType": "String"
  },
  {
    "nickname": "LA",
    "fieldName": "topmostSubform[0].Page1[0].f1_3[0]",
    "fieldType": "String"
  },
  {
    "nickname": "LB",
    "fieldName": "topmostSubform[0].Page1[0].BComb[0].f1_4[0]",
    "fieldType": "String"
  },
  {
    "nickname": "LC",
    "fieldName": "topmostSubform[0].Page1[0].f1_5[0]",
    "fieldType": "String"
  },
  {
    "nickname": "LD",
    "fieldName": "topmostSubform[0].Page1[0].DComb[0].f1_6[0]",
    "fieldType": "String"
  },
  {
    "nickname": "LER1",
    "fieldName": "topmostSubform[0].Page1[0].f1_7[0]",
    "fieldType": "String"
  },
  {
    "nickname": "LER2",
    "fieldName": "topmostSubform[0].Page1[0].f1_8[0]",
    "fieldType": "String"
  },
  {
    "nickname": "CF_Cash",
    "fieldName": "topmostSubform[0].Page1[0].c1_1[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "CF_Accrual",
    "fieldName": "topmostSubform[0].Page1[0].c1_1[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "CF_Other",
    "fieldName": "topmostSubform[0].Page1[0].c1_1[2]",
    "fieldType": "Boolean",
    "checkmark": "3"
  },
  {
    "nickname": "LF",
    "fieldName": "topmostSubform[0].Page1[0].f1_9[0]",
    "fieldType": "String"
  },
  {
    "nickname": "CG_Yes",
    "fieldName": "topmostSubform[0].Page1[0].c1_2[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  },
  {
    "nickname": "CG_No",
    "fieldName": "topmostSubform[0].Page1[0].c1_2[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "CH",
    "fieldName": "topmostSubform[0].Page1[0].c1_3[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "CI_Yes",
    "fieldName": "topmostSubform[0].Page1[0].c1_4[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  },
  {
    "nickname": "CI_No",
    "fieldName": "topmostSubform[0].Page1[0].c1_4[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "CJ_Yes",
    "fieldName": "topmostSubform[0].Page1[0].c1_5[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  },
  {
    "nickname": "CJ_No",
    "fieldName": "topmostSubform[0].Page1[0].c1_5[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "C1",
    "fieldName": "topmostSubform[0].Page1[0].c1_6[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L1",
    "fieldName": "topmostSubform[0].Page1[0].f1_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L2",
    "fieldName": "topmostSubform[0].Page1[0].f1_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L3",
    "fieldName": "topmostSubform[0].Page1[0].f1_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L4",
    "fieldName": "topmostSubform[0].Page1[0].f1_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5",
    "fieldName": "topmostSubform[0].Page1[0].f1_14[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L6",
    "fieldName": "topmostSubform[0].Page1[0].f1_15[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L7",
    "fieldName": "topmostSubform[0].Page1[0].f1_16[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_17[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L9",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_18[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L10",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_19[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L11",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L12",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_21[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L13",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_22[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_23[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L15",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_24[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L16a",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_25[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L16b",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_26[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L17",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_27[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_28[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L19",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_29[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L20a",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_30[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L20b",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_31[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L21",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_32[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_33[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L23",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_34[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L24a",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_35[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L24b",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_36[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L25",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_37[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L26",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_38[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L27a",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_39[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L27b",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_40[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L28",
    "fieldName": "topmostSubform[0].Page1[0].f1_41[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L29",
    "fieldName": "topmostSubform[0].Page1[0].f1_42[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L30a",
    "fieldName": "topmostSubform[0].Page1[0].f1_43[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L30b",
    "fieldName": "topmostSubform[0].Page1[0].f1_44[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L30",
    "fieldName": "topmostSubform[0].Page1[0].f1_45[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L31",
    "fieldName": "topmostSubform[0].Page1[0].f1_46[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C32a",
    "fieldName": "topmostSubform[0].Page1[0].c1_7[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C32b",
    "fieldName": "topmostSubform[0].Page1[0].c1_7[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "C33a",
    "fieldName": "topmostSubform[0].Page2[0].c2_1[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C33b",
    "fieldName": "topmostSubform[0].Page2[0].c2_2[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C33c",
    "fieldName": "topmostSubform[0].Page2[0].c2_3[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C34a",
    "fieldName": "topmostSubform[0].Page2[0].c2_4[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  },
  {
    "nickname": "C34b",
    "fieldName": "topmostSubform[0].Page2[0].c2_4[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "L35",
    "fieldName": "topmostSubform[0].Page2[0].f2_1[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L36",
    "fieldName": "topmostSubform[0].Page2[0].f2_2[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L37",
    "fieldName": "topmostSubform[0].Page2[0].f2_3[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L38",
    "fieldName": "topmostSubform[0].Page2[0].f2_4[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L39",
    "fieldName": "topmostSubform[0].Page2[0].f2_5[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L40",
    "fieldName": "topmostSubform[0].Page2[0].f2_6[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L41",
    "fieldName": "topmostSubform[0].Page2[0].f2_7[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L42",
    "fieldName": "topmostSubform[0].Page2[0].f2_8[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L43_MM",
    "fieldName": "topmostSubform[0].Page2[0].f2_9[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L43_DD",
    "fieldName": "topmostSubform[0].Page2[0].f2_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L43_YY",
    "fieldName": "topmostSubform[0].Page2[0].f2_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L44a",
    "fieldName": "topmostSubform[0].Page2[0].f2_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L44b",
    "fieldName": "topmostSubform[0].Page2[0].f2_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L44c",
    "fieldName": "topmostSubform[0].Page2[0].f2_14[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C45_Yes",
    "fieldName": "topmostSubform[0].Page2[0].c2_5[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  },
  {
    "nickname": "C45_No",
    "fieldName": "topmostSubform[0].Page2[0].c2_5[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "C46_Yes",
    "fieldName": "topmostSubform[0].Page2[0].c2_6[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  },
  {
    "nickname": "C46_No",
    "fieldName": "topmostSubform[0].Page2[0].c2_6[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "C47a_Yes",
    "fieldName": "topmostSubform[0].Page2[0].c2_7[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  },
  {
    "nickname": "C47a_No",
    "fieldName": "topmostSubform[0].Page2[0].c2_7[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "C47b_Yes",
    "fieldName": "topmostSubform[0].Page2[0].c2_8[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  },
  {
    "nickname": "C47b_No",
    "fieldName": "topmostSubform[0].Page2[0].c2_8[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "L48R1_desc",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item1[0].f2_15[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R1_amt",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item1[0].f2_16[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R2_desc",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item2[0].f2_17[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R2_amt",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item2[0].f2_18[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R3_desc",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item3[0].f2_19[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R3_amt",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item3[0].f2_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R4_desc",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item4[0].f2_21[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R4_amt",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item4[0].f2_22[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R5_desc",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item5[0].f2_23[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R5_amt",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item5[0].f2_24[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R6_desc",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item6[0].f2_25[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R6_amt",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item6[0].f2_26[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R7_desc",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item7[0].f2_27[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R7_amt",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item7[0].f2_28[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R8_desc",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item8[0].f2_29[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R8_amt",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item8[0].f2_30[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R9_desc",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item9[0].f2_31[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48R9_amt",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item9[0].f2_32[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48",
    "fieldName": "topmostSubform[0].Page2[0].f2_33[0]",
    "fieldType": "String"
  }
];
