/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface F1040SSE {
  P1_Name?: string;
  P1_SSN?: string;
  P1L1a?: string;
  P1L1b?: string;
  P1L2?: string;
  P1L3?: string;
  P1L4?: string;
  P1L5?: string;
  P1L6?: string;
  P2_Name?: string;
  P2_SSN?: string;
  P2C1_A?: boolean;
  P2L1a?: string;
  P2L1b?: string;
  P2L2?: string;
  P2L3?: string;
  P2L4a?: string;
  P2L4b?: string;
  P2L4c?: string;
  P2L5a?: string;
  P2L5b?: string;
  P2L6?: string;
  P2L7?: string;
  P2L8a?: string;
  P2L8b?: string;
  P2L8c?: string;
  P2L8d?: string;
  P2L9?: string;
  P2L10?: string;
  P2L11?: string;
  P2L12?: string;
  P2L13?: string;
  P2L14?: string;
  P2L15?: string;
  P2L16?: string;
  P2L17?: string;
}


export const f1040sse = [
  {
    "nickname": "P1_Name",
    "fieldName": "topmostSubform[0].Page1[0].f1_1[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P1_SSN",
    "fieldName": "topmostSubform[0].Page1[0].f1_2[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P1L1a",
    "fieldName": "topmostSubform[0].Page1[0].f1_3[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P1L1b",
    "fieldName": "topmostSubform[0].Page1[0].f1_4[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P1L2",
    "fieldName": "topmostSubform[0].Page1[0].f1_5[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P1L3",
    "fieldName": "topmostSubform[0].Page1[0].f1_6[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P1L4",
    "fieldName": "topmostSubform[0].Page1[0].f1_7[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P1L5",
    "fieldName": "topmostSubform[0].Page1[0].TagCorrectingSubform1[0].f1_8[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P1L6",
    "fieldName": "topmostSubform[0].Page1[0].TagCorrectingSubform2[0].f1_9[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2_Name",
    "fieldName": "topmostSubform[0].Page2[0].f2_1[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2_SSN",
    "fieldName": "topmostSubform[0].Page2[0].f2_2[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2C1_A",
    "fieldName": "topmostSubform[0].Page2[0].c2_1[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "P2L1a",
    "fieldName": "topmostSubform[0].Page2[0].f2_3[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2L1b",
    "fieldName": "topmostSubform[0].Page2[0].f2_4[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2L2",
    "fieldName": "topmostSubform[0].Page2[0].f2_5[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2L3",
    "fieldName": "topmostSubform[0].Page2[0].f2_6[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2L4a",
    "fieldName": "topmostSubform[0].Page2[0].f2_7[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2L4b",
    "fieldName": "topmostSubform[0].Page2[0].f2_8[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2L4c",
    "fieldName": "topmostSubform[0].Page2[0].f2_9[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2L5a",
    "fieldName": "topmostSubform[0].Page2[0].f2_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2L5b",
    "fieldName": "topmostSubform[0].Page2[0].f2_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2L6",
    "fieldName": "topmostSubform[0].Page2[0].f2_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2L7",
    "fieldName": "topmostSubform[0].Page2[0].f2_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2L8a",
    "fieldName": "topmostSubform[0].Page2[0].f2_14[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2L8b",
    "fieldName": "topmostSubform[0].Page2[0].f2_15[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2L8c",
    "fieldName": "topmostSubform[0].Page2[0].f2_16[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2L8d",
    "fieldName": "topmostSubform[0].Page2[0].f2_17[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2L9",
    "fieldName": "topmostSubform[0].Page2[0].f2_18[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2L10",
    "fieldName": "topmostSubform[0].Page2[0].f2_19[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2L11",
    "fieldName": "topmostSubform[0].Page2[0].f2_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2L12",
    "fieldName": "topmostSubform[0].Page2[0].f2_21[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2L13",
    "fieldName": "topmostSubform[0].Page2[0].f2_22[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2L14",
    "fieldName": "topmostSubform[0].Page2[0].f2_23[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2L15",
    "fieldName": "topmostSubform[0].Page2[0].f2_24[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2L16",
    "fieldName": "topmostSubform[0].Page2[0].f2_25[0]",
    "fieldType": "String"
  },
  {
    "nickname": "P2L17",
    "fieldName": "topmostSubform[0].Page2[0].f2_26[0]",
    "fieldType": "String"
  }
];
