// This file was automatically generated by taxes/src/mappings/builder.ts

export interface F1040SB {
  Name?: string;
  SSN?: string;
  L1_Name1?: string;
  L1_Amount1?: string;
  L1_Name2?: string;
  L1_Amount2?: string;
  L1_Name3?: string;
  L1_Amount3?: string;
  L1_Name4?: string;
  L1_Amount4?: string;
  L1_Name5?: string;
  L1_Amount5?: string;
  L1_Name6?: string;
  L1_Amount6?: string;
  L1_Name7?: string;
  L1_Amount7?: string;
  L1_Name8?: string;
  L1_Amount8?: string;
  L1_Name9?: string;
  L1_Amount9?: string;
  L1_Name10?: string;
  L1_Amount10?: string;
  L1_Name11?: string;
  L1_Amount11?: string;
  L1_Name12?: string;
  L1_Amount12?: string;
  L1_Name13?: string;
  L1_Amount13?: string;
  L1_Name14?: string;
  L1_Amount14?: string;
  L2?: string;
  L3?: string;
  L4?: string;
  L5_Name1?: string;
  L5_Amount1?: string;
  L5_Name2?: string;
  L5_Amount2?: string;
  L5_Name3?: string;
  L5_Amount3?: string;
  L5_Name4?: string;
  L5_Amount4?: string;
  L5_Name5?: string;
  L5_Amount5?: string;
  L5_Name6?: string;
  L5_Amount6?: string;
  L5_Name7?: string;
  L5_Amount7?: string;
  L5_Name8?: string;
  L5_Amount8?: string;
  L5_Name9?: string;
  L5_Amount9?: string;
  L5_Name10?: string;
  L5_Amount10?: string;
  L5_Name11?: string;
  L5_Amount11?: string;
  L5_Name12?: string;
  L5_Amount12?: string;
  L5_Name13?: string;
  L5_Amount13?: string;
  L5_Name14?: string;
  L5_Amount14?: string;
  L5_Name15?: string;
  L5_Amount15?: string;
  L5_Name16?: string;
  L5_Amount16?: string;
  L6?: string;
  c1_1_0?: boolean;
  C7a?: boolean;
  c1_2_0?: boolean;
  C7b?: boolean;
  L7b?: string;
  c1_3_0?: boolean;
  C8?: boolean;
}

export const f1040sb = [
  {
    "nickname": "Name",
    "fieldName": "topmostSubform[0].Page1[0].f1_1[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SSN",
    "fieldName": "topmostSubform[0].Page1[0].f1_2[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name1",
    "fieldName": "topmostSubform[0].Page1[0].f1_3[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount1",
    "fieldName": "topmostSubform[0].Page1[0].f1_4[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name2",
    "fieldName": "topmostSubform[0].Page1[0].f1_5[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount2",
    "fieldName": "topmostSubform[0].Page1[0].f1_6[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name3",
    "fieldName": "topmostSubform[0].Page1[0].f1_7[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount3",
    "fieldName": "topmostSubform[0].Page1[0].f1_8[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name4",
    "fieldName": "topmostSubform[0].Page1[0].f1_9[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount4",
    "fieldName": "topmostSubform[0].Page1[0].f1_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name5",
    "fieldName": "topmostSubform[0].Page1[0].f1_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount5",
    "fieldName": "topmostSubform[0].Page1[0].f1_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name6",
    "fieldName": "topmostSubform[0].Page1[0].f1_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount6",
    "fieldName": "topmostSubform[0].Page1[0].f1_14[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name7",
    "fieldName": "topmostSubform[0].Page1[0].f1_15[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount7",
    "fieldName": "topmostSubform[0].Page1[0].f1_16[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name8",
    "fieldName": "topmostSubform[0].Page1[0].f1_17[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount8",
    "fieldName": "topmostSubform[0].Page1[0].f1_18[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name9",
    "fieldName": "topmostSubform[0].Page1[0].f1_19[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount9",
    "fieldName": "topmostSubform[0].Page1[0].f1_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name10",
    "fieldName": "topmostSubform[0].Page1[0].f1_21[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount10",
    "fieldName": "topmostSubform[0].Page1[0].f1_22[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name11",
    "fieldName": "topmostSubform[0].Page1[0].f1_23[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount11",
    "fieldName": "topmostSubform[0].Page1[0].f1_24[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name12",
    "fieldName": "topmostSubform[0].Page1[0].f1_25[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount12",
    "fieldName": "topmostSubform[0].Page1[0].f1_26[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name13",
    "fieldName": "topmostSubform[0].Page1[0].f1_27[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount13",
    "fieldName": "topmostSubform[0].Page1[0].f1_28[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name14",
    "fieldName": "topmostSubform[0].Page1[0].f1_29[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount14",
    "fieldName": "topmostSubform[0].Page1[0].f1_30[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L2",
    "fieldName": "topmostSubform[0].Page1[0].f1_31[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L3",
    "fieldName": "topmostSubform[0].Page1[0].f1_32[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L4",
    "fieldName": "topmostSubform[0].Page1[0].f1_33[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name1",
    "fieldName": "topmostSubform[0].Page1[0].f1_34[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount1",
    "fieldName": "topmostSubform[0].Page1[0].f1_35[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name2",
    "fieldName": "topmostSubform[0].Page1[0].f1_36[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount2",
    "fieldName": "topmostSubform[0].Page1[0].f1_37[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name3",
    "fieldName": "topmostSubform[0].Page1[0].f1_38[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount3",
    "fieldName": "topmostSubform[0].Page1[0].f1_39[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name4",
    "fieldName": "topmostSubform[0].Page1[0].f1_40[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount4",
    "fieldName": "topmostSubform[0].Page1[0].f1_41[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name5",
    "fieldName": "topmostSubform[0].Page1[0].f1_42[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount5",
    "fieldName": "topmostSubform[0].Page1[0].f1_43[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name6",
    "fieldName": "topmostSubform[0].Page1[0].f1_44[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount6",
    "fieldName": "topmostSubform[0].Page1[0].f1_45[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name7",
    "fieldName": "topmostSubform[0].Page1[0].f1_46[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount7",
    "fieldName": "topmostSubform[0].Page1[0].f1_47[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name8",
    "fieldName": "topmostSubform[0].Page1[0].f1_48[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount8",
    "fieldName": "topmostSubform[0].Page1[0].f1_49[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name9",
    "fieldName": "topmostSubform[0].Page1[0].f1_50[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount9",
    "fieldName": "topmostSubform[0].Page1[0].f1_51[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name10",
    "fieldName": "topmostSubform[0].Page1[0].f1_52[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount10",
    "fieldName": "topmostSubform[0].Page1[0].f1_53[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name11",
    "fieldName": "topmostSubform[0].Page1[0].f1_54[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount11",
    "fieldName": "topmostSubform[0].Page1[0].f1_55[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name12",
    "fieldName": "topmostSubform[0].Page1[0].f1_56[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount12",
    "fieldName": "topmostSubform[0].Page1[0].f1_57[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name13",
    "fieldName": "topmostSubform[0].Page1[0].f1_58[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount13",
    "fieldName": "topmostSubform[0].Page1[0].f1_59[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name14",
    "fieldName": "topmostSubform[0].Page1[0].f1_60[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount14",
    "fieldName": "topmostSubform[0].Page1[0].f1_61[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name15",
    "fieldName": "topmostSubform[0].Page1[0].f1_62[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount15",
    "fieldName": "topmostSubform[0].Page1[0].f1_63[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name16",
    "fieldName": "topmostSubform[0].Page1[0].f1_64[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount16",
    "fieldName": "topmostSubform[0].Page1[0].f1_65[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L6",
    "fieldName": "topmostSubform[0].Page1[0].f1_66[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C7a",
    "fieldName": "topmostSubform[0].Page1[0].c1_1[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "C7b",
    "fieldName": "topmostSubform[0].Page1[0].c1_2[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "L7b",
    "fieldName": "topmostSubform[0].Page1[0].f1_67[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C8",
    "fieldName": "topmostSubform[0].Page1[0].c1_3[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "c1_1_0",
    "fieldName": "topmostSubform[0].Page1[0].c1_1[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "c1_2_0",
    "fieldName": "topmostSubform[0].Page1[0].c1_2[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "c1_3_0",
    "fieldName": "topmostSubform[0].Page1[0].c1_3[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  }
];
