/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface F2555 {
  Name?: string;
  SSN?: string;
  L1?: string;
  L2?: string;
  L3?: string;
  L4a?: string;
  L4b?: string;
  C5a?: boolean;
  C5b?: boolean;
  C5c?: boolean;
  C5d?: boolean;
  C5e?: boolean;
  L5e?: string;
  L6a?: string;
  C6b?: boolean;
  C6c_Yes?: boolean;
  C6c_No?: boolean;
  L6d?: string;
  L7?: string;
  C8a_Yes?: boolean;
  C8a_No?: boolean;
  L8b?: string;
  L9R1?: string;
  L9R2?: string;
  L10_Began?: string;
  L10_Ended?: string;
  C11a?: boolean;
  C11b?: boolean;
  C11c?: boolean;
  C11d?: boolean;
  C12a_Yes?: boolean;
  C12a_No?: boolean;
  L12b?: string;
  C13a_Yes?: boolean;
  C13a_No?: boolean;
  C13b_Yes?: boolean;
  C13b_No?: boolean;
  L14R1a?: string;
  L14R1b?: string;
  L14R1c?: string;
  L14R1d?: string;
  L14R2a?: string;
  L14R2b?: string;
  L14R2c?: string;
  L14R2d?: string;
  L14R3a?: string;
  L14R3b?: string;
  L14R3c?: string;
  L14R3d?: string;
  L14R4a?: string;
  L14R4b?: string;
  L14R4c?: string;
  L14R4d?: string;
  L14R5a?: string;
  L14R5b?: string;
  L14R5c?: string;
  L14R5d?: string;
  L14R6a?: string;
  L14R6b?: string;
  L14R6c?: string;
  L14R6d?: string;
  L14R7a?: string;
  L14R7b?: string;
  L14R7c?: string;
  L14R7d?: string;
  L14R8a?: string;
  L14R8b?: string;
  L14R8c?: string;
  L14R8d?: string;
  L15aR1?: string;
  L15aR2?: string;
  L15b?: string;
  C15c_Yes?: boolean;
  C15c_No?: boolean;
  C15d_Yes?: boolean;
  C15d_No?: boolean;
  L15eR1?: string;
  L15eR2?: string;
  L16_From?: string;
  L16_Through?: string;
  L17?: string;
  L18R1a?: string;
  L18R1b?: string;
  L18R1c?: string;
  L18R1d?: string;
  L18R1e?: string;
  L18R1f?: string;
  L18R2a?: string;
  L18R2b?: string;
  L18R2c?: string;
  L18R2d?: string;
  L18R2e?: string;
  L18R2f?: string;
  L18R3a?: string;
  L18R3b?: string;
  L18R3c?: string;
  L18R3d?: string;
  L18R3e?: string;
  L18R3f?: string;
  L18R4a?: string;
  L18R4b?: string;
  L18R4c?: string;
  L18R4d?: string;
  L18R4e?: string;
  L18R4f?: string;
  L19?: string;
  L20a?: string;
  L20bR1?: string;
  L20bR2?: string;
  L20b?: string;
  L21a?: string;
  L21b?: string;
  L21c?: string;
  L21dR1?: string;
  L21dR2?: string;
  L21d?: string;
  L22a?: string;
  L22b?: string;
  L22c?: string;
  L22d?: string;
  L22e?: string;
  L22fR1?: string;
  L22fR2?: string;
  L22f?: string;
  L22g?: string;
  L23R1?: string;
  L23R2?: string;
  L23?: string;
  L24?: string;
  L25?: string;
  L26?: string;
  L27?: string;
  C27_Yes?: boolean;
  C27_No?: boolean;
  L28?: string;
  L29a?: string;
  L29b?: string;
  L30?: string;
  L31?: string;
  L32?: string;
  L33?: string;
  L34?: string;
  L35_int?: string;
  L35_dec?: string;
  L36?: string;
  L37?: string;
  L38?: string;
  L39_int?: string;
  L39_dec?: string;
  L40?: string;
  L41?: string;
  L42?: string;
  L43?: string;
  L44?: string;
  L45?: string;
  L46?: string;
  L47?: string;
  L48?: string;
  L49?: string;
  L50?: string;
}


export const f2555 = [
  {
    "nickname": "Name",
    "fieldName": "topmostSubform[0].Page1[0].f1_1[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SSN",
    "fieldName": "topmostSubform[0].Page1[0].f1_2[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1",
    "fieldName": "topmostSubform[0].Page1[0].f1_3[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L2",
    "fieldName": "topmostSubform[0].Page1[0].f1_4[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L3",
    "fieldName": "topmostSubform[0].Page1[0].f1_5[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L4a",
    "fieldName": "topmostSubform[0].Page1[0].f1_6[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L4b",
    "fieldName": "topmostSubform[0].Page1[0].f1_7[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C5a",
    "fieldName": "topmostSubform[0].Page1[0].c1_1[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C5b",
    "fieldName": "topmostSubform[0].Page1[0].c1_2[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C5c",
    "fieldName": "topmostSubform[0].Page1[0].c1_3[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C5d",
    "fieldName": "topmostSubform[0].Page1[0].c1_4[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C5e",
    "fieldName": "topmostSubform[0].Page1[0].c1_5[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L5e",
    "fieldName": "topmostSubform[0].Page1[0].f1_8[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L6a",
    "fieldName": "topmostSubform[0].Page1[0].f1_9[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C6b",
    "fieldName": "topmostSubform[0].Page1[0].c1_6[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C6c_Yes",
    "fieldName": "topmostSubform[0].Page1[0].c1_7[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C6c_No",
    "fieldName": "topmostSubform[0].Page1[0].c1_7[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "L6d",
    "fieldName": "topmostSubform[0].Page1[0].f1_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L7",
    "fieldName": "topmostSubform[0].Page1[0].f1_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C8a_Yes",
    "fieldName": "topmostSubform[0].Page1[0].c1_9[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C8a_No",
    "fieldName": "topmostSubform[0].Page1[0].c1_9[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "L8b",
    "fieldName": "topmostSubform[0].Page1[0].f1_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L9R1",
    "fieldName": "topmostSubform[0].Page1[0].f1_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L9R2",
    "fieldName": "topmostSubform[0].Page1[0].f1_14[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L10_Began",
    "fieldName": "topmostSubform[0].Page1[0].f1_15[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L10_Ended",
    "fieldName": "topmostSubform[0].Page1[0].f1_16[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C11a",
    "fieldName": "topmostSubform[0].Page1[0].c1_11[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C11b",
    "fieldName": "topmostSubform[0].Page1[0].c1_11[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "C11c",
    "fieldName": "topmostSubform[0].Page1[0].c1_11[2]",
    "fieldType": "Boolean",
    "checkmark": "3"
  },
  {
    "nickname": "C11d",
    "fieldName": "topmostSubform[0].Page1[0].c1_11[3]",
    "fieldType": "Boolean",
    "checkmark": "4"
  },
  {
    "nickname": "C12a_Yes",
    "fieldName": "topmostSubform[0].Page1[0].c1_15[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C12a_No",
    "fieldName": "topmostSubform[0].Page1[0].c1_15[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "L12b",
    "fieldName": "topmostSubform[0].Page1[0].f1_17[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C13a_Yes",
    "fieldName": "topmostSubform[0].Page1[0].c1_17[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C13a_No",
    "fieldName": "topmostSubform[0].Page1[0].c1_17[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "C13b_Yes",
    "fieldName": "topmostSubform[0].Page1[0].c1_19[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C13b_No",
    "fieldName": "topmostSubform[0].Page1[0].c1_19[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "L14R1a",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow1[0].f1_18[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R1b",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow1[0].f1_19[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R1c",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow1[0].f1_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R1d",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow1[0].f1_21[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R2a",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow2[0].f1_22[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R2b",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow2[0].f1_23[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R2c",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow2[0].f1_24[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R2d",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow2[0].f1_25[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R3a",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow3[0].f1_26[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R3b",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow3[0].f1_27[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R3c",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow3[0].f1_28[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R3d",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow3[0].f1_29[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R4a",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow4[0].f1_30[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R4b",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow4[0].f1_31[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R4c",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow4[0].f1_32[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R4d",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow4[0].f1_33[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R5a",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow5[0].f1_34[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R5b",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow5[0].f1_35[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R5c",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow5[0].f1_36[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R5d",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow5[0].f1_37[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R6a",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow6[0].f1_38[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R6b",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow6[0].f1_39[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R6c",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow6[0].f1_40[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R6d",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow6[0].f1_41[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R7a",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow7[0].f1_42[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R7b",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow7[0].f1_43[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R7c",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow7[0].f1_44[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R7d",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow7[0].f1_45[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R8a",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow8[0].f1_46[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R8b",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow8[0].f1_47[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R8c",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow8[0].f1_48[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R8d",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow8[0].f1_49[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L15aR1",
    "fieldName": "topmostSubform[0].Page1[0].f1_50[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L15aR2",
    "fieldName": "topmostSubform[0].Page1[0].f1_51[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L15b",
    "fieldName": "topmostSubform[0].Page1[0].f1_52[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C15c_Yes",
    "fieldName": "topmostSubform[0].Page1[0].c1_21[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C15c_No",
    "fieldName": "topmostSubform[0].Page1[0].c1_21[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "C15d_Yes",
    "fieldName": "topmostSubform[0].Page1[0].c1_23[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C15d_No",
    "fieldName": "topmostSubform[0].Page1[0].c1_23[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "L15eR1",
    "fieldName": "topmostSubform[0].Page1[0].f1_53[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L15eR2",
    "fieldName": "topmostSubform[0].Page1[0].f1_54[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L16_From",
    "fieldName": "topmostSubform[0].Page2[0].f2_1[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L16_Through",
    "fieldName": "topmostSubform[0].Page2[0].f2_2[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L17",
    "fieldName": "topmostSubform[0].Page2[0].f2_3[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R1a",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow1[0].f2_4[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R1b",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow1[0].f2_5[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R1c",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow1[0].f2_6[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R1d",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow1[0].f2_7[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R1e",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow1[0].f2_8[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R1f",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow1[0].f2_9[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R2a",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow2[0].f2_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R2b",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow2[0].f2_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R2c",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow2[0].f2_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R2d",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow2[0].f2_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R2e",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow2[0].f2_14[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R2f",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow2[0].f2_15[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R3a",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow3[0].f2_16[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R3b",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow3[0].f2_17[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R3c",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow3[0].f2_18[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R3d",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow3[0].f2_19[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R3e",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow3[0].f2_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R3f",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow3[0].f2_21[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R4a",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow4[0].f2_22[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R4b",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow4[0].f2_23[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R4c",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow4[0].f2_24[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R4d",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow4[0].f2_25[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R4e",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow4[0].f2_26[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R4f",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow4[0].f2_27[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L19",
    "fieldName": "topmostSubform[0].Page2[0].f2_28[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L20a",
    "fieldName": "topmostSubform[0].Page2[0].f2_29[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L20bR1",
    "fieldName": "topmostSubform[0].Page2[0].f2_30[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L20bR2",
    "fieldName": "topmostSubform[0].Page2[0].f2_31[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L20b",
    "fieldName": "topmostSubform[0].Page2[0].f2_32[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L21a",
    "fieldName": "topmostSubform[0].Page2[0].f2_33[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L21b",
    "fieldName": "topmostSubform[0].Page2[0].f2_34[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L21c",
    "fieldName": "topmostSubform[0].Page2[0].f2_35[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L21dR1",
    "fieldName": "topmostSubform[0].Page2[0].f2_36[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L21dR2",
    "fieldName": "topmostSubform[0].Page2[0].f2_37[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L21d",
    "fieldName": "topmostSubform[0].Page2[0].f2_38[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22a",
    "fieldName": "topmostSubform[0].Page2[0].f2_39[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22b",
    "fieldName": "topmostSubform[0].Page2[0].f2_40[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22c",
    "fieldName": "topmostSubform[0].Page2[0].f2_41[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22d",
    "fieldName": "topmostSubform[0].Page2[0].f2_42[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22e",
    "fieldName": "topmostSubform[0].Page2[0].f2_43[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22fR1",
    "fieldName": "topmostSubform[0].Page2[0].f2_44[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22fR2",
    "fieldName": "topmostSubform[0].Page2[0].f2_45[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22f",
    "fieldName": "topmostSubform[0].Page2[0].f2_46[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22g",
    "fieldName": "topmostSubform[0].Page2[0].f2_47[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L23R1",
    "fieldName": "topmostSubform[0].Page2[0].f2_48[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L23R2",
    "fieldName": "topmostSubform[0].Page2[0].f2_49[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L23",
    "fieldName": "topmostSubform[0].Page2[0].f2_50[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L24",
    "fieldName": "topmostSubform[0].Page2[0].f2_51[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L25",
    "fieldName": "topmostSubform[0].Page2[0].f2_52[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L26",
    "fieldName": "topmostSubform[0].Page2[0].f2_53[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L27",
    "fieldName": "topmostSubform[0].Page3[0].f3_1[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C27_Yes",
    "fieldName": "topmostSubform[0].Page3[0].c3_1[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C27_No",
    "fieldName": "topmostSubform[0].Page3[0].c3_1[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "L28",
    "fieldName": "topmostSubform[0].Page3[0].f3_2[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L29a",
    "fieldName": "topmostSubform[0].Page3[0].f3_3[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L29b",
    "fieldName": "topmostSubform[0].Page3[0].f3_4[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L30",
    "fieldName": "topmostSubform[0].Page3[0].f3_5[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L31",
    "fieldName": "topmostSubform[0].Page3[0].f3_6[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L32",
    "fieldName": "topmostSubform[0].Page3[0].f3_7[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L33",
    "fieldName": "topmostSubform[0].Page3[0].f3_8[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L34",
    "fieldName": "topmostSubform[0].Page3[0].f3_9[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L35_int",
    "fieldName": "topmostSubform[0].Page3[0].f3_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L35_dec",
    "fieldName": "topmostSubform[0].Page3[0].f3_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L36",
    "fieldName": "topmostSubform[0].Page3[0].f3_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L37",
    "fieldName": "topmostSubform[0].Page3[0].f3_21[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L38",
    "fieldName": "topmostSubform[0].Page3[0].f3_22[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L39_int",
    "fieldName": "topmostSubform[0].Page3[0].f3_23[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L39_dec",
    "fieldName": "topmostSubform[0].Page3[0].f3_24[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L40",
    "fieldName": "topmostSubform[0].Page3[0].f3_25[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L41",
    "fieldName": "topmostSubform[0].Page3[0].f3_28[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L42",
    "fieldName": "topmostSubform[0].Page3[0].f3_29[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L43",
    "fieldName": "topmostSubform[0].Page3[0].f3_30[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L44",
    "fieldName": "topmostSubform[0].Page3[0].f3_31[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L45",
    "fieldName": "topmostSubform[0].Page3[0].f3_32[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L46",
    "fieldName": "topmostSubform[0].Page3[0].f3_33[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L47",
    "fieldName": "topmostSubform[0].Page3[0].f3_34[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48",
    "fieldName": "topmostSubform[0].Page3[0].f3_35[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L49",
    "fieldName": "topmostSubform[0].Page3[0].f3_36[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L50",
    "fieldName": "topmostSubform[0].Page3[0].f3_37[0]",
    "fieldType": "String"
  }
];
