/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface F2555 {
  f1_1_0?: string;
  f1_2_0?: string;
  f1_3_0?: string;
  f1_4_0?: string;
  f1_5_0?: string;
  f1_6_0?: string;
  f1_7_0?: string;
  c1_1_0?: boolean;
  c1_2_0?: boolean;
  c1_3_0?: boolean;
  c1_4_0?: boolean;
  c1_5_0?: boolean;
  f1_8_0?: string;
  f1_9_0?: string;
  c1_6_0?: boolean;
  c1_7_0?: boolean;
  c1_7_1?: boolean;
  f1_10_0?: string;
  f1_11_0?: string;
  c1_9_0?: boolean;
  c1_9_1?: boolean;
  f1_12_0?: string;
  f1_13_0?: string;
  f1_14_0?: string;
  f1_15_0?: string;
  f1_16_0?: string;
  c1_11_0?: boolean;
  c1_11_1?: boolean;
  c1_11_2?: boolean;
  c1_11_3?: boolean;
  c1_15_0?: boolean;
  c1_15_1?: boolean;
  f1_17_0?: string;
  c1_17_0?: boolean;
  c1_17_1?: boolean;
  c1_19_0?: boolean;
  c1_19_1?: boolean;
  f1_18_0?: string;
  f1_19_0?: string;
  f1_20_0?: string;
  f1_21_0?: string;
  f1_22_0?: string;
  f1_23_0?: string;
  f1_24_0?: string;
  f1_25_0?: string;
  f1_26_0?: string;
  f1_27_0?: string;
  f1_28_0?: string;
  f1_29_0?: string;
  f1_30_0?: string;
  f1_31_0?: string;
  f1_32_0?: string;
  f1_33_0?: string;
  f1_34_0?: string;
  f1_35_0?: string;
  f1_36_0?: string;
  f1_37_0?: string;
  f1_38_0?: string;
  f1_39_0?: string;
  f1_40_0?: string;
  f1_41_0?: string;
  f1_42_0?: string;
  f1_43_0?: string;
  f1_44_0?: string;
  f1_45_0?: string;
  f1_46_0?: string;
  f1_47_0?: string;
  f1_48_0?: string;
  f1_49_0?: string;
  f1_50_0?: string;
  f1_51_0?: string;
  f1_52_0?: string;
  c1_21_0?: boolean;
  c1_21_1?: boolean;
  c1_23_0?: boolean;
  c1_23_1?: boolean;
  f1_53_0?: string;
  f1_54_0?: string;
  f2_1_0?: string;
  f2_2_0?: string;
  f2_3_0?: string;
  f2_4_0?: string;
  f2_5_0?: string;
  f2_6_0?: string;
  f2_7_0?: string;
  f2_8_0?: string;
  f2_9_0?: string;
  f2_10_0?: string;
  f2_11_0?: string;
  f2_12_0?: string;
  f2_13_0?: string;
  f2_14_0?: string;
  f2_15_0?: string;
  f2_16_0?: string;
  f2_17_0?: string;
  f2_18_0?: string;
  f2_19_0?: string;
  f2_20_0?: string;
  f2_21_0?: string;
  f2_22_0?: string;
  f2_23_0?: string;
  f2_24_0?: string;
  f2_25_0?: string;
  f2_26_0?: string;
  f2_27_0?: string;
  f2_28_0?: string;
  f2_29_0?: string;
  f2_30_0?: string;
  f2_31_0?: string;
  f2_32_0?: string;
  f2_33_0?: string;
  f2_34_0?: string;
  f2_35_0?: string;
  f2_36_0?: string;
  f2_37_0?: string;
  f2_38_0?: string;
  f2_39_0?: string;
  f2_40_0?: string;
  f2_41_0?: string;
  f2_42_0?: string;
  f2_43_0?: string;
  f2_44_0?: string;
  f2_45_0?: string;
  f2_46_0?: string;
  f2_47_0?: string;
  f2_48_0?: string;
  f2_49_0?: string;
  f2_50_0?: string;
  f2_51_0?: string;
  f2_52_0?: string;
  f2_53_0?: string;
  f3_1_0?: string;
  c3_1_0?: boolean;
  c3_1_1?: boolean;
  f3_2_0?: string;
  f3_3_0?: string;
  f3_4_0?: string;
  f3_5_0?: string;
  f3_6_0?: string;
  f3_7_0?: string;
  f3_8_0?: string;
  f3_9_0?: string;
  f3_10_0?: string;
  f3_11_0?: string;
  f3_20_0?: string;
  f3_21_0?: string;
  f3_22_0?: string;
  f3_23_0?: string;
  f3_24_0?: string;
  f3_25_0?: string;
  f3_28_0?: string;
  f3_29_0?: string;
  f3_30_0?: string;
  f3_31_0?: string;
  f3_32_0?: string;
  f3_33_0?: string;
  f3_34_0?: string;
  f3_35_0?: string;
  f3_36_0?: string;
  f3_37_0?: string;
}


export const f2555 = [
  {
    "nickname": "Name",
    "fieldName": "topmostSubform[0].Page1[0].f1_1[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SSN",
    "fieldName": "topmostSubform[0].Page1[0].f1_2[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1",
    "fieldName": "topmostSubform[0].Page1[0].f1_3[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L2",
    "fieldName": "topmostSubform[0].Page1[0].f1_4[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L3",
    "fieldName": "topmostSubform[0].Page1[0].f1_5[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L4a",
    "fieldName": "topmostSubform[0].Page1[0].f1_6[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L4b",
    "fieldName": "topmostSubform[0].Page1[0].f1_7[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C5a",
    "fieldName": "topmostSubform[0].Page1[0].c1_1[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C5b",
    "fieldName": "topmostSubform[0].Page1[0].c1_2[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C5c",
    "fieldName": "topmostSubform[0].Page1[0].c1_3[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C5d",
    "fieldName": "topmostSubform[0].Page1[0].c1_4[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C5e",
    "fieldName": "topmostSubform[0].Page1[0].c1_5[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L5e",
    "fieldName": "topmostSubform[0].Page1[0].f1_8[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L6a",
    "fieldName": "topmostSubform[0].Page1[0].f1_9[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C6b",
    "fieldName": "topmostSubform[0].Page1[0].c1_6[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C6c_Yes",
    "fieldName": "topmostSubform[0].Page1[0].c1_7[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C6c_No",
    "fieldName": "topmostSubform[0].Page1[0].c1_7[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "L6d",
    "fieldName": "topmostSubform[0].Page1[0].f1_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L7",
    "fieldName": "topmostSubform[0].Page1[0].f1_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C8a_Yes",
    "fieldName": "topmostSubform[0].Page1[0].c1_9[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C8a_No",
    "fieldName": "topmostSubform[0].Page1[0].c1_9[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "L8b",
    "fieldName": "topmostSubform[0].Page1[0].f1_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L9R1",
    "fieldName": "topmostSubform[0].Page1[0].f1_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L9R2",
    "fieldName": "topmostSubform[0].Page1[0].f1_14[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L10_Began",
    "fieldName": "topmostSubform[0].Page1[0].f1_15[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L10_Ended",
    "fieldName": "topmostSubform[0].Page1[0].f1_16[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C11a",
    "fieldName": "topmostSubform[0].Page1[0].c1_11[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C11b",
    "fieldName": "topmostSubform[0].Page1[0].c1_11[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "C11c",
    "fieldName": "topmostSubform[0].Page1[0].c1_11[2]",
    "fieldType": "Boolean",
    "checkmark": "3"
  },
  {
    "nickname": "C11d",
    "fieldName": "topmostSubform[0].Page1[0].c1_11[3]",
    "fieldType": "Boolean",
    "checkmark": "4"
  },
  {
    "nickname": "C12a_Yes",
    "fieldName": "topmostSubform[0].Page1[0].c1_15[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C12a_No",
    "fieldName": "topmostSubform[0].Page1[0].c1_15[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "L12b",
    "fieldName": "topmostSubform[0].Page1[0].f1_17[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C13a_Yes",
    "fieldName": "topmostSubform[0].Page1[0].c1_17[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C13a_No",
    "fieldName": "topmostSubform[0].Page1[0].c1_17[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "C13b_Yes",
    "fieldName": "topmostSubform[0].Page1[0].c1_19[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C13b_No",
    "fieldName": "topmostSubform[0].Page1[0].c1_19[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "L14R1a",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow1[0].f1_18[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R1b",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow1[0].f1_19[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R1c",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow1[0].f1_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R1d",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow1[0].f1_21[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R2a",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow2[0].f1_22[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R2b",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow2[0].f1_23[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R2c",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow2[0].f1_24[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R2d",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow2[0].f1_25[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R3a",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow3[0].f1_26[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R3b",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow3[0].f1_27[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R3c",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow3[0].f1_28[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R3d",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow3[0].f1_29[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R4a",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow4[0].f1_30[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R4b",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow4[0].f1_31[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R4c",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow4[0].f1_32[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R4d",
    "fieldName": "topmostSubform[0].Page1[0].Table1_Line14[0].BodyRow4[0].f1_33[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R5a",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow5[0].f1_34[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R5b",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow5[0].f1_35[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R5c",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow5[0].f1_36[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R5d",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow5[0].f1_37[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R6a",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow6[0].f1_38[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R6b",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow6[0].f1_39[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R6c",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow6[0].f1_40[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R6d",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow6[0].f1_41[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R7a",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow7[0].f1_42[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R7b",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow7[0].f1_43[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R7c",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow7[0].f1_44[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R7d",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow7[0].f1_45[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R8a",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow8[0].f1_46[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R8b",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow8[0].f1_47[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R8c",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow8[0].f1_48[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14R8d",
    "fieldName": "topmostSubform[0].Page1[0].Table2_Line14[0].BodyRow8[0].f1_49[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L15aR1",
    "fieldName": "topmostSubform[0].Page1[0].f1_50[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L15aR2",
    "fieldName": "topmostSubform[0].Page1[0].f1_51[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L15b",
    "fieldName": "topmostSubform[0].Page1[0].f1_52[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C15c_Yes",
    "fieldName": "topmostSubform[0].Page1[0].c1_21[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C15c_No",
    "fieldName": "topmostSubform[0].Page1[0].c1_21[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "C15d_Yes",
    "fieldName": "topmostSubform[0].Page1[0].c1_23[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C15d_No",
    "fieldName": "topmostSubform[0].Page1[0].c1_23[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "L15eR1",
    "fieldName": "topmostSubform[0].Page1[0].f1_53[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L15eR2",
    "fieldName": "topmostSubform[0].Page1[0].f1_54[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L16_From",
    "fieldName": "topmostSubform[0].Page2[0].f2_1[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L16_Through",
    "fieldName": "topmostSubform[0].Page2[0].f2_2[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L17",
    "fieldName": "topmostSubform[0].Page2[0].f2_3[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R1a",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow1[0].f2_4[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R1b",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow1[0].f2_5[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R1c",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow1[0].f2_6[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R1d",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow1[0].f2_7[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R1e",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow1[0].f2_8[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R1f",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow1[0].f2_9[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R2a",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow2[0].f2_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R2b",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow2[0].f2_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R2c",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow2[0].f2_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R2d",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow2[0].f2_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R2e",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow2[0].f2_14[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R2f",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow2[0].f2_15[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R3a",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow3[0].f2_16[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R3b",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow3[0].f2_17[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R3c",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow3[0].f2_18[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R3d",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow3[0].f2_19[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R3e",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow3[0].f2_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R3f",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow3[0].f2_21[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R4a",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow4[0].f2_22[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R4b",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow4[0].f2_23[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R4c",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow4[0].f2_24[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R4d",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow4[0].f2_25[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R4e",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow4[0].f2_26[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18R4f",
    "fieldName": "topmostSubform[0].Page2[0].Table_Line18[0].BodyRow4[0].f2_27[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L19",
    "fieldName": "topmostSubform[0].Page2[0].f2_28[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L20a",
    "fieldName": "topmostSubform[0].Page2[0].f2_29[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L20bR1",
    "fieldName": "topmostSubform[0].Page2[0].f2_30[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L20bR2",
    "fieldName": "topmostSubform[0].Page2[0].f2_31[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L20b",
    "fieldName": "topmostSubform[0].Page2[0].f2_32[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L21a",
    "fieldName": "topmostSubform[0].Page2[0].f2_33[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L21b",
    "fieldName": "topmostSubform[0].Page2[0].f2_34[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L21c",
    "fieldName": "topmostSubform[0].Page2[0].f2_35[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L21dR1",
    "fieldName": "topmostSubform[0].Page2[0].f2_36[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L21dR2",
    "fieldName": "topmostSubform[0].Page2[0].f2_37[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L21d",
    "fieldName": "topmostSubform[0].Page2[0].f2_38[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22a",
    "fieldName": "topmostSubform[0].Page2[0].f2_39[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22b",
    "fieldName": "topmostSubform[0].Page2[0].f2_40[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22c",
    "fieldName": "topmostSubform[0].Page2[0].f2_41[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22d",
    "fieldName": "topmostSubform[0].Page2[0].f2_42[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22e",
    "fieldName": "topmostSubform[0].Page2[0].f2_43[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22fR1",
    "fieldName": "topmostSubform[0].Page2[0].f2_44[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22fR2",
    "fieldName": "topmostSubform[0].Page2[0].f2_45[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22f",
    "fieldName": "topmostSubform[0].Page2[0].f2_46[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22g",
    "fieldName": "topmostSubform[0].Page2[0].f2_47[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L23R1",
    "fieldName": "topmostSubform[0].Page2[0].f2_48[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L23R2",
    "fieldName": "topmostSubform[0].Page2[0].f2_49[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L23",
    "fieldName": "topmostSubform[0].Page2[0].f2_50[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L24",
    "fieldName": "topmostSubform[0].Page2[0].f2_51[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L25",
    "fieldName": "topmostSubform[0].Page2[0].f2_52[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L26",
    "fieldName": "topmostSubform[0].Page2[0].f2_53[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L27",
    "fieldName": "topmostSubform[0].Page3[0].f3_1[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C27_Yes",
    "fieldName": "topmostSubform[0].Page3[0].c3_1[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C27_No",
    "fieldName": "topmostSubform[0].Page3[0].c3_1[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "L28",
    "fieldName": "topmostSubform[0].Page3[0].f3_2[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L29a",
    "fieldName": "topmostSubform[0].Page3[0].f3_3[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L29b",
    "fieldName": "topmostSubform[0].Page3[0].f3_4[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L30",
    "fieldName": "topmostSubform[0].Page3[0].f3_5[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L31",
    "fieldName": "topmostSubform[0].Page3[0].f3_6[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L32",
    "fieldName": "topmostSubform[0].Page3[0].f3_7[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L33",
    "fieldName": "topmostSubform[0].Page3[0].f3_8[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L34",
    "fieldName": "topmostSubform[0].Page3[0].f3_9[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L35_int",
    "fieldName": "topmostSubform[0].Page3[0].f3_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L35_dec",
    "fieldName": "topmostSubform[0].Page3[0].f3_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L36",
    "fieldName": "topmostSubform[0].Page3[0].f3_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L37",
    "fieldName": "topmostSubform[0].Page3[0].f3_21[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L38",
    "fieldName": "topmostSubform[0].Page3[0].f3_22[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L39_int",
    "fieldName": "topmostSubform[0].Page3[0].f3_23[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L39_dec",
    "fieldName": "topmostSubform[0].Page3[0].f3_24[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L40",
    "fieldName": "topmostSubform[0].Page3[0].f3_25[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L41",
    "fieldName": "topmostSubform[0].Page3[0].f3_28[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L42",
    "fieldName": "topmostSubform[0].Page3[0].f3_29[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L43",
    "fieldName": "topmostSubform[0].Page3[0].f3_30[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L44",
    "fieldName": "topmostSubform[0].Page3[0].f3_31[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L45",
    "fieldName": "topmostSubform[0].Page3[0].f3_32[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L46",
    "fieldName": "topmostSubform[0].Page3[0].f3_33[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L47",
    "fieldName": "topmostSubform[0].Page3[0].f3_34[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48",
    "fieldName": "topmostSubform[0].Page3[0].f3_35[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L49",
    "fieldName": "topmostSubform[0].Page3[0].f3_36[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L50",
    "fieldName": "topmostSubform[0].Page3[0].f3_37[0]",
    "fieldType": "String"
  }
];
