/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface F8889 {
  f1_1_0?: string;
  f1_2_0?: string;
  c1_1_0?: boolean;
  c1_1_1?: boolean;
  f1_3_0?: string;
  f1_4_0?: string;
  f1_5_0?: string;
  f1_6_0?: string;
  f1_7_0?: string;
  f1_8_0?: string;
  f1_9_0?: string;
  f1_10_0?: string;
  f1_11_0?: string;
  f1_12_0?: string;
  f1_13_0?: string;
  f1_14_0?: string;
  f1_15_0?: string;
  f1_16_0?: string;
  f1_17_0?: string;
  f1_18_0?: string;
  f1_19_0?: string;
  c1_2_0?: boolean;
  f1_20_0?: string;
  f2_1_0?: string;
  f2_2_0?: string;
  f2_3_0?: string;
  f2_4_0?: string;
}


export const f8889 = [
  {
    "nickname": "Name",
    "fieldName": "topmostSubform[0].Page1[0].f1_1[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SSN",
    "fieldName": "topmostSubform[0].Page1[0].f1_2[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C1_Self",
    "fieldName": "topmostSubform[0].Page1[0].c1_1[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C1_Family",
    "fieldName": "topmostSubform[0].Page1[0].c1_1[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "L2",
    "fieldName": "topmostSubform[0].Page1[0].f1_3[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L3",
    "fieldName": "topmostSubform[0].Page1[0].f1_4[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L4",
    "fieldName": "topmostSubform[0].Page1[0].f1_5[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5",
    "fieldName": "topmostSubform[0].Page1[0].f1_6[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L6",
    "fieldName": "topmostSubform[0].Page1[0].f1_7[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L7",
    "fieldName": "topmostSubform[0].Page1[0].f1_8[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8",
    "fieldName": "topmostSubform[0].Page1[0].f1_9[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L9",
    "fieldName": "topmostSubform[0].Page1[0].f1_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L10",
    "fieldName": "topmostSubform[0].Page1[0].f1_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L11",
    "fieldName": "topmostSubform[0].Page1[0].f1_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L12",
    "fieldName": "topmostSubform[0].Page1[0].f1_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L13",
    "fieldName": "topmostSubform[0].Page1[0].f1_14[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14a",
    "fieldName": "topmostSubform[0].Page1[0].f1_15[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14b",
    "fieldName": "topmostSubform[0].Page1[0].f1_16[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14c",
    "fieldName": "topmostSubform[0].Page1[0].f1_17[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L15",
    "fieldName": "topmostSubform[0].Page1[0].f1_18[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L16",
    "fieldName": "topmostSubform[0].Page1[0].f1_19[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C17a",
    "fieldName": "topmostSubform[0].Page1[0].c1_2[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L17b",
    "fieldName": "topmostSubform[0].Page1[0].f1_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18",
    "fieldName": "topmostSubform[0].Page2[0].f2_1[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L19",
    "fieldName": "topmostSubform[0].Page2[0].f2_2[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L20",
    "fieldName": "topmostSubform[0].Page2[0].f2_3[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L21",
    "fieldName": "topmostSubform[0].Page2[0].f2_4[0]",
    "fieldType": "String"
  }
];
