stages:
 - build
 - test
 - deploy

build:
  image: docker:stable
  stage: build
  services:
    - name: docker:dind
      alias: localhost
  only:
    refs:
      - branches
  script:
    - apk add bash curl git jq make
    - make pull-latest
    - make all
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - make push

test:
  image: docker:stable
  stage: test
  services:
    - name: docker:dind
      alias: localhost
  only:
    refs:
      - branches
  script:
    - apk add bash curl git jq make
    - make test-utils
    - make test-transactions
    - make test-core
    - make run-example
    - make start-prod
    - make dls
    - bash ops/health-check.sh server
    - bash ops/health-check.sh webserver
    - bash ops/health-check.sh proxy
