export const assets = {

  AAVE: "AAVE",
  stkAAVE: "stkAAVE",

  aAAVE: "aAAVE",
  aBAL: "aBAL",
  aBAT: "aBAT",
  aBUSD: "aBUSD",
  aCRV: "aCRV",
  aDAI: "aDAI",
  aENJ: "aENJ",
  aGUSD: "aGUSD",
  aKNC: "aKNC",
  aLINK: "aLINK",
  aMANA: "aMANA",
  aMKR: "aMKR",
  aRAI: "aRAI",
  aREN: "aREN",
  aRENFIL: "aRENFIL",
  aSNX: "aSNX",
  aSUSD: "aSUSD",
  aTUSD: "aTUSD",
  aUSDC: "aUSDC",
  aUSDT: "aUSDT",
  aWBTC: "aWBTC",
  aWETH: "aWETH",
  aXSUSHI: "aXSUSHI",
  aYFI: "aYFI",
  aZRX: "aZRX",

  amAAVE: "amAAVE",
  amDAI: "amDAI",
  amMATIC: "amMATIC",
  amUSDC: "amUSDC",
  amUSDT: "amUSDT",
  amWBTC: "amWBTC",
  amWETH: "amWETH",

} as const;
