/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface F1040S2 {
  Name?: string;
  SSN?: string;
  L1?: string;
  L2?: string;
  L3?: string;
  L4?: string;
  C5a?: boolean;
  C5b?: boolean;
  L5?: string;
  L6?: string;
  L7a?: string;
  L7b?: string;
  C8a?: boolean;
  C8b?: boolean;
  C8c?: boolean;
  L8c?: string;
  L8?: string;
  L9?: string;
  L10?: string;
}


export const f1040s2 = [
  {
    "nickname": "Name",
    "fieldName": "form1[0].Page1[0].f1_01[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SSN",
    "fieldName": "form1[0].Page1[0].f1_02[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1",
    "fieldName": "form1[0].Page1[0].f1_03[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L2",
    "fieldName": "form1[0].Page1[0].f1_04[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L3",
    "fieldName": "form1[0].Page1[0].f1_05[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L4",
    "fieldName": "form1[0].Page1[0].f1_06[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C5a",
    "fieldName": "form1[0].Page1[0].c1_1[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C5b",
    "fieldName": "form1[0].Page1[0].c1_2[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L5",
    "fieldName": "form1[0].Page1[0].f1_07[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L6",
    "fieldName": "form1[0].Page1[0].f1_08[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L7a",
    "fieldName": "form1[0].Page1[0].f1_09[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L7b",
    "fieldName": "form1[0].Page1[0].f1_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C8a",
    "fieldName": "form1[0].Page1[0].Line8[0].c1_3[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C8b",
    "fieldName": "form1[0].Page1[0].Line8[0].c1_4[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C8c",
    "fieldName": "form1[0].Page1[0].Line8[0].c1_5[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L8c",
    "fieldName": "form1[0].Page1[0].Line8[0].f1_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8",
    "fieldName": "form1[0].Page1[0].f1_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L9",
    "fieldName": "form1[0].Page1[0].f1_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L10",
    "fieldName": "form1[0].Page1[0].f1_14[0]",
    "fieldType": "String"
  }
];
