/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface F1040S3 {
  Name?: string;
  SSN?: string;
  L1?: string;
  L2?: string;
  L3?: string;
  L4?: string;
  L5?: string;
  C6a?: boolean;
  C6b?: boolean;
  C6c?: boolean;
  L6c?: string;
  L6?: string;
  L7?: string;
  L8?: string;
  L9?: string;
  L10?: string;
  L11?: string;
  L12a?: string;
  L12b?: string;
  L12c?: string;
  L12d_Etc?: string;
  L12d?: string;
  L12e?: string;
  L12f?: string;
  L13?: string;
}


export const f1040s3 = [
  {
    "nickname": "Name",
    "fieldName": "form1[0].Page1[0].f1_01[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SSN",
    "fieldName": "form1[0].Page1[0].f1_02[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1",
    "fieldName": "form1[0].Page1[0].f1_03[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L2",
    "fieldName": "form1[0].Page1[0].f1_04[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L3",
    "fieldName": "form1[0].Page1[0].f1_05[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L4",
    "fieldName": "form1[0].Page1[0].f1_06[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5",
    "fieldName": "form1[0].Page1[0].f1_07[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C6a",
    "fieldName": "form1[0].Page1[0].c1_1[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C6b",
    "fieldName": "form1[0].Page1[0].c1_2[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C6c",
    "fieldName": "form1[0].Page1[0].c1_3[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L6c",
    "fieldName": "form1[0].Page1[0].f1_08[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L6",
    "fieldName": "form1[0].Page1[0].f1_09[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L7",
    "fieldName": "form1[0].Page1[0].f1_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8",
    "fieldName": "form1[0].Page1[0].f1_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L9",
    "fieldName": "form1[0].Page1[0].f1_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L10",
    "fieldName": "form1[0].Page1[0].f1_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L11",
    "fieldName": "form1[0].Page1[0].f1_14[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L12a",
    "fieldName": "form1[0].Page1[0].Line12_ReadOrder[0].f1_15[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L12b",
    "fieldName": "form1[0].Page1[0].f1_16[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L12c",
    "fieldName": "form1[0].Page1[0].f1_17[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L12d_Etc",
    "fieldName": "form1[0].Page1[0].f1_18[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L12d",
    "fieldName": "form1[0].Page1[0].f1_19[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L12e",
    "fieldName": "form1[0].Page1[0].f1_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L12f",
    "fieldName": "form1[0].Page1[0].f1_21[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L13",
    "fieldName": "form1[0].Page1[0].f1_22[0]",
    "fieldType": "String"
  }
];
