/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface F1040Sse {
  f1_01_0?: string;
  f1_02_0?: string;
  c1_1_0?: boolean;
  f1_03_0?: string;
  f1_04_0?: string;
  f1_05_0?: string;
  f1_06_0?: string;
  f1_07_0?: string;
  f1_08_0?: string;
  f1_09_0?: string;
  f1_10_0?: string;
  f1_11_0?: string;
  f1_12_0?: string;
  f1_13_0?: string;
  f1_14_0?: string;
  f1_15_0?: string;
  f1_16_0?: string;
  f1_17_0?: string;
  f1_18_0?: string;
  f1_19_0?: string;
  f1_20_0?: string;
  f1_21_0?: string;
  f1_22_0?: string;
  f1_23_0?: string;
  f1_24_0?: string;
  f1_25_0?: string;
  f1_26_0?: string;
  f2_01_0?: string;
  f2_02_0?: string;
  f2_03_0?: string;
  f2_04_0?: string;
  f2_05_0?: string;
  f2_06_0?: string;
  f2_07_0?: string;
  f2_08_0?: string;
  f2_09_0?: string;
}


export const f1040sse = [
  {
    "nickname": "Name",
    "fieldName": "topmostSubform[0].Page1[0].f1_01[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SSN",
    "fieldName": "topmostSubform[0].Page1[0].f1_02[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C0_A",
    "fieldName": "topmostSubform[0].Page1[0].c1_1[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L1a",
    "fieldName": "topmostSubform[0].Page1[0].f1_03[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1b",
    "fieldName": "topmostSubform[0].Page1[0].f1_04[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L2",
    "fieldName": "topmostSubform[0].Page1[0].f1_05[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L3",
    "fieldName": "topmostSubform[0].Page1[0].f1_06[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L4a",
    "fieldName": "topmostSubform[0].Page1[0].f1_07[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L4b",
    "fieldName": "topmostSubform[0].Page1[0].f1_08[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L4c",
    "fieldName": "topmostSubform[0].Page1[0].f1_09[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5a",
    "fieldName": "topmostSubform[0].Page1[0].Line5a_ReadOrder[0].f1_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5b",
    "fieldName": "topmostSubform[0].Page1[0].f1_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L6",
    "fieldName": "topmostSubform[0].Page1[0].f1_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8a",
    "fieldName": "topmostSubform[0].Page1[0].Line8a_ReadOrder[0].f1_14[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8b",
    "fieldName": "topmostSubform[0].Page1[0].f1_15[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8c",
    "fieldName": "topmostSubform[0].Page1[0].f1_16[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8d",
    "fieldName": "topmostSubform[0].Page1[0].f1_17[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L9",
    "fieldName": "topmostSubform[0].Page1[0].f1_18[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L10",
    "fieldName": "topmostSubform[0].Page1[0].f1_19[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L11",
    "fieldName": "topmostSubform[0].Page1[0].f1_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L12",
    "fieldName": "topmostSubform[0].Page1[0].f1_21[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L13",
    "fieldName": "topmostSubform[0].Page1[0].f1_22[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L15",
    "fieldName": "topmostSubform[0].Page1[0].f1_24[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L16",
    "fieldName": "topmostSubform[0].Page1[0].f1_25[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L17",
    "fieldName": "topmostSubform[0].Page1[0].f1_26[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18",
    "fieldName": "topmostSubform[0].Page2[0].f2_01[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L19",
    "fieldName": "topmostSubform[0].Page2[0].f2_02[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L20",
    "fieldName": "topmostSubform[0].Page2[0].f2_03[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L21",
    "fieldName": "topmostSubform[0].Page2[0].f2_04[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22",
    "fieldName": "topmostSubform[0].Page2[0].f2_05[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L23",
    "fieldName": "topmostSubform[0].Page2[0].f2_06[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L24",
    "fieldName": "topmostSubform[0].Page2[0].f2_07[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L25",
    "fieldName": "topmostSubform[0].Page2[0].f2_08[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L26",
    "fieldName": "topmostSubform[0].Page2[0].f2_09[0]",
    "fieldType": "String"
  },
  {
    "nickname": "Noop2",
    "fieldName": "topmostSubform[0].Page1[0].f1_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "Noop3",
    "fieldName": "topmostSubform[0].Page1[0].f1_23[0]",
    "fieldType": "String"
  }
];
