/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface F1040Sd {
  f1_01_0?: string;
  f1_02_0?: string;
  c1_1_0?: boolean;
  c1_1_1?: boolean;
  f1_03_0?: string;
  f1_04_0?: string;
  f1_05_RO_0?: string;
  f1_06_0?: string;
  f1_07_0?: string;
  f1_08_0?: string;
  f1_09_0?: string;
  f1_10_0?: string;
  f1_11_0?: string;
  f1_12_0?: string;
  f1_13_0?: string;
  f1_14_0?: string;
  f1_15_0?: string;
  f1_16_0?: string;
  f1_17_0?: string;
  f1_18_0?: string;
  f1_19_0?: string;
  f1_20_0?: string;
  f1_21_0?: string;
  f1_22_0?: string;
  f1_23_0?: string;
  f1_24_0?: string;
  f1_25_RO_0?: string;
  f1_26_0?: string;
  f1_27_0?: string;
  f1_28_0?: string;
  f1_29_0?: string;
  f1_30_0?: string;
  f1_31_0?: string;
  f1_32_0?: string;
  f1_33_0?: string;
  f1_34_0?: string;
  f1_35_0?: string;
  f1_36_0?: string;
  f1_37_0?: string;
  f1_38_0?: string;
  f1_39_0?: string;
  f1_40_0?: string;
  f1_41_0?: string;
  f1_42_0?: string;
  f1_43_0?: string;
  f2_01_0?: string;
  c2_1_0?: boolean;
  c2_1_1?: boolean;
  f2_02_0?: string;
  f2_03_0?: string;
  c2_2_0?: boolean;
  c2_2_1?: boolean;
  f2_04_0?: string;
  c2_3_0?: boolean;
  c2_3_1?: boolean;
}


export const f1040sd = [
  {
    "nickname": "Name",
    "fieldName": "topmostSubform[0].Page1[0].f1_01[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SSN",
    "fieldName": "topmostSubform[0].Page1[0].f1_02[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C0_No",
    "fieldName": "topmostSubform[0].Page1[0].c1_1[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "L1a_d",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartI[0].Row1a[0].f1_03[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1a_e",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartI[0].Row1a[0].f1_04[0]",
    "fieldType": "String"
  },
  {
    "nickname": "RO_L1a_f",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartI[0].Row1a[0].f1_05_RO[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1a_h",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartI[0].Row1a[0].f1_06[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1b_d",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartI[0].Row1b[0].f1_07[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1b_e",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartI[0].Row1b[0].f1_08[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1b_g",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartI[0].Row1b[0].f1_09[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1b_h",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartI[0].Row1b[0].f1_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L2_d",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartI[0].Row2[0].f1_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L2_e",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartI[0].Row2[0].f1_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L2_g",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartI[0].Row2[0].f1_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L2_h",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartI[0].Row2[0].f1_14[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L3_d",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartI[0].Row3[0].f1_15[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L3_e",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartI[0].Row3[0].f1_16[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L3_g",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartI[0].Row3[0].f1_17[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L3_h",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartI[0].Row3[0].f1_18[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L4",
    "fieldName": "topmostSubform[0].Page1[0].f1_19[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5",
    "fieldName": "topmostSubform[0].Page1[0].f1_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L6",
    "fieldName": "topmostSubform[0].Page1[0].f1_21[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L7",
    "fieldName": "topmostSubform[0].Page1[0].f1_22[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8a_d",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartII[0].Row8a[0].f1_23[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8a_e",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartII[0].Row8a[0].f1_24[0]",
    "fieldType": "String"
  },
  {
    "nickname": "RO_L8a_f",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartII[0].Row8a[0].f1_25_RO[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8a_h",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartII[0].Row8a[0].f1_26[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8b_d",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartII[0].Row8b[0].f1_27[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8b_e",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartII[0].Row8b[0].f1_28[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8b_g",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartII[0].Row8b[0].f1_29[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8b_h",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartII[0].Row8b[0].f1_30[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L9_d",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartII[0].Row9[0].f1_31[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L9_e",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartII[0].Row9[0].f1_32[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L9_g",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartII[0].Row9[0].f1_33[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L9_h",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartII[0].Row9[0].f1_34[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L10_d",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartII[0].Row10[0].f1_35[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L10_e",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartII[0].Row10[0].f1_36[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L10_g",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartII[0].Row10[0].f1_37[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L10_h",
    "fieldName": "topmostSubform[0].Page1[0].Table_PartII[0].Row10[0].f1_38[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L11",
    "fieldName": "topmostSubform[0].Page1[0].f1_39[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L12",
    "fieldName": "topmostSubform[0].Page1[0].f1_40[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L13",
    "fieldName": "topmostSubform[0].Page1[0].f1_41[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14",
    "fieldName": "topmostSubform[0].Page1[0].f1_42[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L15",
    "fieldName": "topmostSubform[0].Page1[0].f1_43[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L16",
    "fieldName": "topmostSubform[0].Page2[0].f2_01[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C17_Yes",
    "fieldName": "topmostSubform[0].Page2[0].c2_1[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C17_No",
    "fieldName": "topmostSubform[0].Page2[0].c2_1[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "L18",
    "fieldName": "topmostSubform[0].Page2[0].f2_02[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L19",
    "fieldName": "topmostSubform[0].Page2[0].f2_03[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C20_No",
    "fieldName": "topmostSubform[0].Page2[0].c2_2[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "L21",
    "fieldName": "topmostSubform[0].Page2[0].f2_04[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C22_Yes",
    "fieldName": "topmostSubform[0].Page2[0].c2_3[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C22_No",
    "fieldName": "topmostSubform[0].Page2[0].c2_3[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "C0_Noop2",
    "fieldName": "topmostSubform[0].Page2[0].c2_2[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C0_Noop4",
    "fieldName": "topmostSubform[0].Page1[0].c1_1[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  }
];
