/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface F1040 {
  c1_01_0?: boolean;
  c1_01_1?: boolean;
  c1_01_2?: boolean;
  c1_01_3?: boolean;
  c1_01_4?: boolean;
  f1_01_0?: string;
  f1_02_0?: string;
  f1_03_0?: string;
  f1_04_0?: string;
  f1_05_0?: string;
  f1_06_0?: string;
  f1_07_0?: string;
  f1_08_0?: string;
  f1_09_0?: string;
  f1_10_0?: string;
  f1_11_0?: string;
  f1_12_0?: string;
  f1_13_0?: string;
  f1_14_0?: string;
  f1_15_0?: string;
  c1_02_0?: boolean;
  c1_03_0?: boolean;
  c1_04_0?: boolean;
  c1_04_1?: boolean;
  c1_05_0?: boolean;
  c1_06_0?: boolean;
  c1_07_0?: boolean;
  c1_08_0?: boolean;
  c1_09_0?: boolean;
  c1_10_0?: boolean;
  c1_11_0?: boolean;
  c1_12_0?: boolean;
  f1_16_0?: string;
  f1_17_0?: string;
  f1_18_0?: string;
  c1_13_0?: boolean;
  c1_14_0?: boolean;
  f1_19_0?: string;
  f1_20_0?: string;
  f1_21_0?: string;
  c1_15_0?: boolean;
  c1_16_0?: boolean;
  f1_22_0?: string;
  f1_23_0?: string;
  f1_24_0?: string;
  c1_17_0?: boolean;
  c1_18_0?: boolean;
  f1_25_0?: string;
  f1_26_0?: string;
  f1_27_0?: string;
  c1_19_0?: boolean;
  c1_20_0?: boolean;
  f1_28_0?: string;
  f1_29_0?: string;
  f1_30_0?: string;
  f1_31_0?: string;
  f1_32_0?: string;
  f1_33_0?: string;
  f1_34_0?: string;
  f1_35_0?: string;
  f1_36_0?: string;
  f1_37_0?: string;
  f1_38_0?: string;
  c1_21_0?: boolean;
  f1_39_0?: string;
  f1_40_0?: string;
  f1_41_0?: string;
  f1_42_0?: string;
  f1_43_0?: string;
  f1_44_0?: string;
  f1_45_0?: string;
  f1_46_0?: string;
  f1_47_0?: string;
  f1_48_0?: string;
  f1_49_0?: string;
  c2_01_0?: boolean;
  c2_02_0?: boolean;
  c2_03_0?: boolean;
  f2_01_0?: string;
  f2_02_0?: string;
  f2_03_0?: string;
  f2_04_0?: string;
  f2_05_0?: string;
  f2_06_0?: string;
  f2_07_0?: string;
  f2_08_0?: string;
  f2_09_0?: string;
  f2_10_0?: string;
  f2_11_0?: string;
  f2_12_0?: string;
  f2_13_0?: string;
  f2_14_0?: string;
  f2_15_0?: string;
  f2_16_0?: string;
  f2_17_0?: string;
  f2_18_0?: string;
  f2_19_0?: string;
  f2_20_0?: string;
  f2_21_0?: string;
  f2_22_0?: string;
  f2_23_0?: string;
  c2_04_0?: boolean;
  f2_24_0?: string;
  f2_25_0?: string;
  c2_05_0?: boolean;
  c2_05_1?: boolean;
  f2_26_0?: string;
  f2_27_0?: string;
  f2_28_0?: string;
  f2_32_0?: string;
  c2_6_0?: boolean;
  c2_6_1?: boolean;
  f2_33_0?: string;
  f2_34_0?: string;
  f2_35_0?: string;
  f2_36_0?: string;
  f2_37_0?: string;
  f2_38_0?: string;
  f2_39_0?: string;
  f2_40_0?: string;
  f2_41_0?: string;
  f2_42_0?: string;
  f2_43_0?: string;
  c2_07_0?: boolean;
  f2_44_0?: string;
  f2_45_0?: string;
  f2_46_0?: string;
  f2_47_0?: string;
}


export const f1040 = [
  {
    "nickname": "Single",
    "fieldName": "topmostSubform[0].Page1[0].FilingStatus[0].c1_01[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "MarriedJoint",
    "fieldName": "topmostSubform[0].Page1[0].FilingStatus[0].c1_01[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "MarriedSeparate",
    "fieldName": "topmostSubform[0].Page1[0].FilingStatus[0].c1_01[2]",
    "fieldType": "Boolean",
    "checkmark": "3"
  },
  {
    "nickname": "HeadOfHousehold",
    "fieldName": "topmostSubform[0].Page1[0].FilingStatus[0].c1_01[3]",
    "fieldType": "Boolean",
    "checkmark": "4"
  },
  {
    "nickname": "Widow",
    "fieldName": "topmostSubform[0].Page1[0].FilingStatus[0].c1_01[4]",
    "fieldType": "Boolean",
    "checkmark": "5"
  },
  {
    "nickname": "StatusInfo",
    "fieldName": "topmostSubform[0].Page1[0].FilingStatus[0].f1_01[0]",
    "fieldType": "String"
  },
  {
    "nickname": "FirstNameMI",
    "fieldName": "topmostSubform[0].Page1[0].f1_02[0]",
    "fieldType": "String"
  },
  {
    "nickname": "LastName",
    "fieldName": "topmostSubform[0].Page1[0].f1_03[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SSN",
    "fieldName": "topmostSubform[0].Page1[0].YourSocial[0].f1_04[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SpouseFirstNameMI",
    "fieldName": "topmostSubform[0].Page1[0].f1_05[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SpouseLastName",
    "fieldName": "topmostSubform[0].Page1[0].f1_06[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SpouseSSN",
    "fieldName": "topmostSubform[0].Page1[0].SpousesSocial[0].f1_07[0]",
    "fieldType": "String"
  },
  {
    "nickname": "StreetAddress",
    "fieldName": "topmostSubform[0].Page1[0].Address[0].f1_08[0]",
    "fieldType": "String"
  },
  {
    "nickname": "Apt",
    "fieldName": "topmostSubform[0].Page1[0].Address[0].f1_09[0]",
    "fieldType": "String"
  },
  {
    "nickname": "City",
    "fieldName": "topmostSubform[0].Page1[0].Address[0].f1_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "State",
    "fieldName": "topmostSubform[0].Page1[0].Address[0].f1_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "Zip",
    "fieldName": "topmostSubform[0].Page1[0].Address[0].f1_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "ForeignCountry",
    "fieldName": "topmostSubform[0].Page1[0].Address[0].f1_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "ForeignState",
    "fieldName": "topmostSubform[0].Page1[0].Address[0].f1_14[0]",
    "fieldType": "String"
  },
  {
    "nickname": "ForeignZip",
    "fieldName": "topmostSubform[0].Page1[0].Address[0].f1_15[0]",
    "fieldType": "String"
  },
  {
    "nickname": "PresidentialWweFund",
    "fieldName": "topmostSubform[0].Page1[0].c1_02[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "PresidentialWweFundSpouse",
    "fieldName": "topmostSubform[0].Page1[0].c1_03[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "HasCrypto_Yes",
    "fieldName": "topmostSubform[0].Page1[0].c1_04[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "HasCrypto_No",
    "fieldName": "topmostSubform[0].Page1[0].c1_04[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "Dependent",
    "fieldName": "topmostSubform[0].Page1[0].c1_05[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "SpouseDependent",
    "fieldName": "topmostSubform[0].Page1[0].c1_06[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "SpouseSeparate",
    "fieldName": "topmostSubform[0].Page1[0].c1_07[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "IsOld",
    "fieldName": "topmostSubform[0].Page1[0].c1_08[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "IsBlind",
    "fieldName": "topmostSubform[0].Page1[0].c1_09[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "HasOldSpouse",
    "fieldName": "topmostSubform[0].Page1[0].c1_10[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "HasBlindSpouse",
    "fieldName": "topmostSubform[0].Page1[0].c1_11[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "MoreThanFourDependnts",
    "fieldName": "topmostSubform[0].Page1[0].Dependents_ReadOrder[0].c1_12[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C0_D1_IsChildTaxCredit",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow1[0].c1_13[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C0_D1_IsOtherDependent",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow1[0].c1_14[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C0_D2_IsOtherDependent",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow2[0].c1_16[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C0_D3_IsChildTaxCredit",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow3[0].c1_17[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C0_D3_IsOtherDependent",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow3[0].c1_18[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C0_D4_IsChildTaxCredit",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow4[0].c1_19[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C0_D4_IsOtherDependent",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow4[0].c1_20[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "D1_Name",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow1[0].f1_16[0]",
    "fieldType": "String"
  },
  {
    "nickname": "D1_SSN",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow1[0].f1_17[0]",
    "fieldType": "String"
  },
  {
    "nickname": "D1_Rel",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow1[0].f1_18[0]",
    "fieldType": "String"
  },
  {
    "nickname": "D2_Name",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow2[0].f1_19[0]",
    "fieldType": "String"
  },
  {
    "nickname": "D2_SSN",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow2[0].f1_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "D2_Rel",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow2[0].f1_21[0]",
    "fieldType": "String"
  },
  {
    "nickname": "D3_Name",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow3[0].f1_22[0]",
    "fieldType": "String"
  },
  {
    "nickname": "D3_SSN",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow3[0].f1_23[0]",
    "fieldType": "String"
  },
  {
    "nickname": "D3_Rel",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow3[0].f1_24[0]",
    "fieldType": "String"
  },
  {
    "nickname": "D4_Name",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow4[0].f1_25[0]",
    "fieldType": "String"
  },
  {
    "nickname": "D4_SSN",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow4[0].f1_26[0]",
    "fieldType": "String"
  },
  {
    "nickname": "D4_Rel",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow4[0].f1_27[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_28[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L2a",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_29[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L2b",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_30[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L3a",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_31[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L3b",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_32[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L4a",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_33[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L4b",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_34[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5a",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_35[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5b",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_36[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L6a",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_37[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L6b",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_38[0]",
    "fieldType": "String"
  },
  {
    "nickname": "HasCapGains",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].c1_21[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L7",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_39[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_40[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L9",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_41[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L10a",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].Line10-12_ReadOrder[0].f1_42[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L10b",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].Line10-12_ReadOrder[0].f1_43[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L10c",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_44[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L11",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_45[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L12",
    "fieldName": "topmostSubform[0].Page1[0].f1_46[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L13",
    "fieldName": "topmostSubform[0].Page1[0].f1_47[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14",
    "fieldName": "topmostSubform[0].Page1[0].f1_48[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L15",
    "fieldName": "topmostSubform[0].Page1[0].f1_49[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L16_0",
    "fieldName": "topmostSubform[0].Page2[0].c2_01[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L16_1",
    "fieldName": "topmostSubform[0].Page2[0].c2_02[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L16_2",
    "fieldName": "topmostSubform[0].Page2[0].c2_03[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L16_3",
    "fieldName": "topmostSubform[0].Page2[0].f2_01[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L16",
    "fieldName": "topmostSubform[0].Page2[0].f2_02[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L17",
    "fieldName": "topmostSubform[0].Page2[0].f2_03[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18",
    "fieldName": "topmostSubform[0].Page2[0].f2_04[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L19",
    "fieldName": "topmostSubform[0].Page2[0].f2_05[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L20",
    "fieldName": "topmostSubform[0].Page2[0].f2_06[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L21",
    "fieldName": "topmostSubform[0].Page2[0].f2_07[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22",
    "fieldName": "topmostSubform[0].Page2[0].f2_08[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L23",
    "fieldName": "topmostSubform[0].Page2[0].f2_09[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L24",
    "fieldName": "topmostSubform[0].Page2[0].f2_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L25a",
    "fieldName": "topmostSubform[0].Page2[0].Line25_ReadOrder[0].f2_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L25b",
    "fieldName": "topmostSubform[0].Page2[0].Line25_ReadOrder[0].f2_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L25c",
    "fieldName": "topmostSubform[0].Page2[0].Line25_ReadOrder[0].f2_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L25d",
    "fieldName": "topmostSubform[0].Page2[0].Lines26-27_ReadOrder[0].f2_14[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L26",
    "fieldName": "topmostSubform[0].Page2[0].Lines26-27_ReadOrder[0].f2_15[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C25",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow2[0].c1_15[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L27",
    "fieldName": "topmostSubform[0].Page2[0].Lines27-32_ReadOrder[0].f2_16[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L28",
    "fieldName": "topmostSubform[0].Page2[0].Lines27-32_ReadOrder[0].f2_17[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L29",
    "fieldName": "topmostSubform[0].Page2[0].Lines27-32_ReadOrder[0].f2_18[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L30",
    "fieldName": "topmostSubform[0].Page2[0].Lines27-32_ReadOrder[0].f2_19[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L31",
    "fieldName": "topmostSubform[0].Page2[0].Lines27-32_ReadOrder[0].f2_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L32",
    "fieldName": "topmostSubform[0].Page2[0].Line32-33_ReadOrder[0].f2_21[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L33",
    "fieldName": "topmostSubform[0].Page2[0].f2_22[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L34",
    "fieldName": "topmostSubform[0].Page2[0].f2_23[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C35a",
    "fieldName": "topmostSubform[0].Page2[0].c2_04[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C35b",
    "fieldName": "topmostSubform[0].Page2[0].c2_05[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C35c",
    "fieldName": "topmostSubform[0].Page2[0].c2_6[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L35a",
    "fieldName": "topmostSubform[0].Page2[0].f2_24[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L35b",
    "fieldName": "topmostSubform[0].Page2[0].RoutingNo[0].f2_25[0]",
    "fieldType": "String"
  },
  {
    "nickname": "IsChecking",
    "fieldName": "topmostSubform[0].Page2[0].c2_05[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "L35d",
    "fieldName": "topmostSubform[0].Page2[0].AccountNo[0].f2_26[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L36",
    "fieldName": "topmostSubform[0].Page2[0].f2_27[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L37",
    "fieldName": "topmostSubform[0].Page2[0].f2_28[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L38",
    "fieldName": "topmostSubform[0].Page2[0].f2_32[0]",
    "fieldType": "String"
  },
  {
    "nickname": "DesignateThirdParty",
    "fieldName": "topmostSubform[0].Page2[0].c2_6[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "ThirdPartyName",
    "fieldName": "topmostSubform[0].Page2[0].f2_33[0]",
    "fieldType": "String"
  },
  {
    "nickname": "ThirdPartyPhone",
    "fieldName": "topmostSubform[0].Page2[0].f2_34[0]",
    "fieldType": "String"
  },
  {
    "nickname": "ThirdPartyPin",
    "fieldName": "topmostSubform[0].Page2[0].f2_35[0]",
    "fieldType": "String"
  },
  {
    "nickname": "Occupation",
    "fieldName": "topmostSubform[0].Page2[0].f2_36[0]",
    "fieldType": "String"
  },
  {
    "nickname": "PIN",
    "fieldName": "topmostSubform[0].Page2[0].f2_37[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SpouseOccupation",
    "fieldName": "topmostSubform[0].Page2[0].f2_38[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SpousePIN",
    "fieldName": "topmostSubform[0].Page2[0].f2_39[0]",
    "fieldType": "String"
  },
  {
    "nickname": "PhoneNumber",
    "fieldName": "topmostSubform[0].Page2[0].f2_40[0]",
    "fieldType": "String"
  },
  {
    "nickname": "Email",
    "fieldName": "topmostSubform[0].Page2[0].f2_41[0]",
    "fieldType": "String"
  },
  {
    "nickname": "PreparerName",
    "fieldName": "topmostSubform[0].Page2[0].f2_42[0]",
    "fieldType": "String"
  },
  {
    "nickname": "PreparerPTIN",
    "fieldName": "topmostSubform[0].Page2[0].f2_43[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SelfEmployed",
    "fieldName": "topmostSubform[0].Page2[0].c2_07[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "PreparerFirm",
    "fieldName": "topmostSubform[0].Page2[0].f2_44[0]",
    "fieldType": "String"
  },
  {
    "nickname": "PreparerPhone",
    "fieldName": "topmostSubform[0].Page2[0].f2_45[0]",
    "fieldType": "String"
  },
  {
    "nickname": "PreparerAddress",
    "fieldName": "topmostSubform[0].Page2[0].f2_46[0]",
    "fieldType": "String"
  },
  {
    "nickname": "PreparerEIN",
    "fieldName": "topmostSubform[0].Page2[0].f2_47[0]",
    "fieldType": "String"
  }
];
