/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface F1040Sb {
  f1_1_0?: string;
  f1_2_0?: string;
  f1_3_0?: string;
  f1_4_0?: string;
  f1_5_0?: string;
  f1_6_0?: string;
  f1_7_0?: string;
  f1_8_0?: string;
  f1_9_0?: string;
  f1_10_0?: string;
  f1_11_0?: string;
  f1_12_0?: string;
  f1_13_0?: string;
  f1_14_0?: string;
  f1_15_0?: string;
  f1_16_0?: string;
  f1_17_0?: string;
  f1_18_0?: string;
  f1_19_0?: string;
  f1_20_0?: string;
  f1_21_0?: string;
  f1_22_0?: string;
  f1_23_0?: string;
  f1_24_0?: string;
  f1_25_0?: string;
  f1_26_0?: string;
  f1_27_0?: string;
  f1_28_0?: string;
  f1_29_0?: string;
  f1_30_0?: string;
  f1_31_0?: string;
  f1_32_0?: string;
  f1_33_0?: string;
  f1_34_0?: string;
  f1_35_0?: string;
  f1_36_0?: string;
  f1_37_0?: string;
  f1_38_0?: string;
  f1_39_0?: string;
  f1_40_0?: string;
  f1_41_0?: string;
  f1_42_0?: string;
  f1_43_0?: string;
  f1_44_0?: string;
  f1_45_0?: string;
  f1_46_0?: string;
  f1_47_0?: string;
  f1_48_0?: string;
  f1_49_0?: string;
  f1_50_0?: string;
  f1_51_0?: string;
  f1_52_0?: string;
  f1_53_0?: string;
  f1_54_0?: string;
  f1_55_0?: string;
  f1_56_0?: string;
  f1_57_0?: string;
  f1_58_0?: string;
  f1_59_0?: string;
  f1_60_0?: string;
  f1_61_0?: string;
  f1_62_0?: string;
  f1_63_0?: string;
  f1_64_0?: string;
  f1_65_0?: string;
  f1_66_0?: string;
  c1_1_0?: boolean;
  c1_1_1?: boolean;
  c1_2_0?: boolean;
  c1_2_1?: boolean;
  f1_67_0?: string;
  c1_3_0?: boolean;
  c1_3_1?: boolean;
}


export const f1040sb = [
  {
    "nickname": "Name",
    "fieldName": "topmostSubform[0].Page1[0].f1_1[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SSN",
    "fieldName": "topmostSubform[0].Page1[0].f1_2[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name1",
    "fieldName": "topmostSubform[0].Page1[0].f1_3[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount1",
    "fieldName": "topmostSubform[0].Page1[0].f1_4[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name2",
    "fieldName": "topmostSubform[0].Page1[0].f1_5[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount2",
    "fieldName": "topmostSubform[0].Page1[0].f1_6[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name3",
    "fieldName": "topmostSubform[0].Page1[0].f1_7[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount3",
    "fieldName": "topmostSubform[0].Page1[0].f1_8[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name4",
    "fieldName": "topmostSubform[0].Page1[0].f1_9[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount4",
    "fieldName": "topmostSubform[0].Page1[0].f1_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name5",
    "fieldName": "topmostSubform[0].Page1[0].f1_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount5",
    "fieldName": "topmostSubform[0].Page1[0].f1_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name6",
    "fieldName": "topmostSubform[0].Page1[0].f1_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount6",
    "fieldName": "topmostSubform[0].Page1[0].f1_14[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name7",
    "fieldName": "topmostSubform[0].Page1[0].f1_15[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount7",
    "fieldName": "topmostSubform[0].Page1[0].f1_16[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name8",
    "fieldName": "topmostSubform[0].Page1[0].f1_17[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount8",
    "fieldName": "topmostSubform[0].Page1[0].f1_18[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name9",
    "fieldName": "topmostSubform[0].Page1[0].f1_19[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount9",
    "fieldName": "topmostSubform[0].Page1[0].f1_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name10",
    "fieldName": "topmostSubform[0].Page1[0].f1_21[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount10",
    "fieldName": "topmostSubform[0].Page1[0].f1_22[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name11",
    "fieldName": "topmostSubform[0].Page1[0].f1_23[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount11",
    "fieldName": "topmostSubform[0].Page1[0].f1_24[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name12",
    "fieldName": "topmostSubform[0].Page1[0].f1_25[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount12",
    "fieldName": "topmostSubform[0].Page1[0].f1_26[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name13",
    "fieldName": "topmostSubform[0].Page1[0].f1_27[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount13",
    "fieldName": "topmostSubform[0].Page1[0].f1_28[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Name14",
    "fieldName": "topmostSubform[0].Page1[0].f1_29[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1_Amount14",
    "fieldName": "topmostSubform[0].Page1[0].f1_30[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L2",
    "fieldName": "topmostSubform[0].Page1[0].f1_31[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L3",
    "fieldName": "topmostSubform[0].Page1[0].f1_32[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L4",
    "fieldName": "topmostSubform[0].Page1[0].f1_33[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name1",
    "fieldName": "topmostSubform[0].Page1[0].f1_34[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount1",
    "fieldName": "topmostSubform[0].Page1[0].f1_35[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name2",
    "fieldName": "topmostSubform[0].Page1[0].f1_36[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount2",
    "fieldName": "topmostSubform[0].Page1[0].f1_37[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name3",
    "fieldName": "topmostSubform[0].Page1[0].f1_38[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount3",
    "fieldName": "topmostSubform[0].Page1[0].f1_39[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name4",
    "fieldName": "topmostSubform[0].Page1[0].f1_40[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount4",
    "fieldName": "topmostSubform[0].Page1[0].f1_41[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name5",
    "fieldName": "topmostSubform[0].Page1[0].f1_42[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount5",
    "fieldName": "topmostSubform[0].Page1[0].f1_43[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name6",
    "fieldName": "topmostSubform[0].Page1[0].f1_44[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount6",
    "fieldName": "topmostSubform[0].Page1[0].f1_45[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name7",
    "fieldName": "topmostSubform[0].Page1[0].f1_46[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount7",
    "fieldName": "topmostSubform[0].Page1[0].f1_47[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name8",
    "fieldName": "topmostSubform[0].Page1[0].f1_48[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount8",
    "fieldName": "topmostSubform[0].Page1[0].f1_49[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name9",
    "fieldName": "topmostSubform[0].Page1[0].f1_50[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount9",
    "fieldName": "topmostSubform[0].Page1[0].f1_51[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name10",
    "fieldName": "topmostSubform[0].Page1[0].f1_52[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount10",
    "fieldName": "topmostSubform[0].Page1[0].f1_53[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name11",
    "fieldName": "topmostSubform[0].Page1[0].f1_54[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount11",
    "fieldName": "topmostSubform[0].Page1[0].f1_55[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name12",
    "fieldName": "topmostSubform[0].Page1[0].f1_56[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount12",
    "fieldName": "topmostSubform[0].Page1[0].f1_57[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name13",
    "fieldName": "topmostSubform[0].Page1[0].f1_58[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount13",
    "fieldName": "topmostSubform[0].Page1[0].f1_59[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name14",
    "fieldName": "topmostSubform[0].Page1[0].f1_60[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount14",
    "fieldName": "topmostSubform[0].Page1[0].f1_61[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name15",
    "fieldName": "topmostSubform[0].Page1[0].f1_62[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount15",
    "fieldName": "topmostSubform[0].Page1[0].f1_63[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Name16",
    "fieldName": "topmostSubform[0].Page1[0].f1_64[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5_Amount16",
    "fieldName": "topmostSubform[0].Page1[0].f1_65[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L6",
    "fieldName": "topmostSubform[0].Page1[0].f1_66[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C7a",
    "fieldName": "topmostSubform[0].Page1[0].c1_1[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "C7b",
    "fieldName": "topmostSubform[0].Page1[0].c1_2[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "L7b",
    "fieldName": "topmostSubform[0].Page1[0].f1_67[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C8",
    "fieldName": "topmostSubform[0].Page1[0].c1_3[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "C0_Noop1",
    "fieldName": "topmostSubform[0].Page1[0].c1_1[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C0_Noop2",
    "fieldName": "topmostSubform[0].Page1[0].c1_2[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C0_Noop3",
    "fieldName": "topmostSubform[0].Page1[0].c1_3[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  }
];
