/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface F1040SC {
  Name?: string;
  SSN?: string;
  L0_A?: string;
  L0_B?: string;
  L0_C?: string;
  L0_D?: string;
  L0_E_Address?: string;
  L0_E_CityZip?: string;
  c1_1_0?: boolean;
  c1_1_1?: boolean;
  C_F?: boolean;
  L0_F?: string;
  c1_2_0?: boolean;
  L0_F_Accrual?: boolean;
  C0_G?: boolean;
  c1_4_0?: boolean;
  C0_H?: boolean;
  c1_5_0?: boolean;
  C0_I?: boolean;
  C0_J?: boolean;
  L1?: string;
  L2?: string;
  L3?: string;
  L4?: string;
  L5?: string;
  L6?: string;
  L7?: string;
  L8?: string;
  L9?: string;
  L10?: string;
  L11?: string;
  L12?: string;
  L13?: string;
  L14?: string;
  L15?: string;
  L16a?: string;
  L16b?: string;
  L17?: string;
  L18?: string;
  L19?: string;
  L20a?: string;
  L20b?: string;
  L21?: string;
  L22?: string;
  L23?: string;
  L24a?: string;
  L24b?: string;
  L25?: string;
  L26?: string;
  L27a?: string;
  RO_L27b?: string;
  L28?: string;
  L29?: string;
  L30_TotalSize?: string;
  L30_WorkSize?: string;
  L30?: string;
  L31?: string;
  c1_7_0?: boolean;
  C32a?: boolean;
  C32b?: boolean;
  C33a?: boolean;
  C34b?: boolean;
  c2_4_0?: boolean;
  C34c?: boolean;
  L35?: string;
  L36?: string;
  L37?: string;
  L38?: string;
  L39?: string;
  L40?: string;
  L41?: string;
  L42?: string;
  L43_MM?: string;
  L43_DD?: string;
  L43_YY?: string;
  L44a?: string;
  L44b?: string;
  L44c?: string;
  c2_5_0?: boolean;
  L45_NO?: boolean;
  c2_6_0?: boolean;
  L46_NO?: boolean;
  c2_7_0?: boolean;
  L47a_NO?: boolean;
  c2_8_0?: boolean;
  L47b_NO?: boolean;
  L48_Expense1?: string;
  L48_Amount1?: string;
  L48_Expense2?: string;
  L48_Amount2?: string;
  L48_Expense3?: string;
  L48_Amount3?: string;
  L48_Expense4?: string;
  L48_Amount4?: string;
  L48_Expense5?: string;
  L48_Amount5?: string;
  L48_Expense6?: string;
  L48_Amount6?: string;
  L48_Expense7?: string;
  L48_Amount7?: string;
  L48_Expense8?: string;
  L48_Amount8?: string;
  L48_Expense9?: string;
  L48_Amount9?: string;
  L48?: string;
}


export const f1040sc = [
  {
    "nickname": "Name",
    "fieldName": "topmostSubform[0].Page1[0].f1_1[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SSN",
    "fieldName": "topmostSubform[0].Page1[0].f1_2[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L0_A",
    "fieldName": "topmostSubform[0].Page1[0].f1_3[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L0_B",
    "fieldName": "topmostSubform[0].Page1[0].BComb[0].f1_4[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L0_C",
    "fieldName": "topmostSubform[0].Page1[0].f1_5[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L0_D",
    "fieldName": "topmostSubform[0].Page1[0].DComb[0].f1_6[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L0_E_Address",
    "fieldName": "topmostSubform[0].Page1[0].f1_7[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L0_E_CityZip",
    "fieldName": "topmostSubform[0].Page1[0].f1_8[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C_F",
    "fieldName": "topmostSubform[0].Page1[0].c1_1[2]",
    "fieldType": "Boolean",
    "checkmark": "3"
  },
  {
    "nickname": "L0_F",
    "fieldName": "topmostSubform[0].Page1[0].f1_9[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L0_F_Accrual",
    "fieldName": "topmostSubform[0].Page1[0].c1_2[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "C0_G",
    "fieldName": "topmostSubform[0].Page1[0].c1_3[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C0_H",
    "fieldName": "topmostSubform[0].Page1[0].c1_4[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "C0_I",
    "fieldName": "topmostSubform[0].Page1[0].c1_5[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "C0_J",
    "fieldName": "topmostSubform[0].Page1[0].c1_6[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L1",
    "fieldName": "topmostSubform[0].Page1[0].f1_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L2",
    "fieldName": "topmostSubform[0].Page1[0].f1_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L3",
    "fieldName": "topmostSubform[0].Page1[0].f1_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L4",
    "fieldName": "topmostSubform[0].Page1[0].f1_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5",
    "fieldName": "topmostSubform[0].Page1[0].f1_14[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L6",
    "fieldName": "topmostSubform[0].Page1[0].f1_15[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L7",
    "fieldName": "topmostSubform[0].Page1[0].f1_16[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_17[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L9",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_18[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L10",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_19[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L11",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L12",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_21[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L13",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_22[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_23[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L15",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_24[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L16a",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_25[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L16b",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_26[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L17",
    "fieldName": "topmostSubform[0].Page1[0].Lines8-17[0].f1_27[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_28[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L19",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_29[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L20a",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_30[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L20b",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_31[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L21",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_32[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_33[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L23",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_34[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L24a",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_35[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L24b",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_36[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L25",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_37[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L26",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_38[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L27a",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_39[0]",
    "fieldType": "String"
  },
  {
    "nickname": "RO_L27b",
    "fieldName": "topmostSubform[0].Page1[0].Lines18-27[0].f1_40[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L28",
    "fieldName": "topmostSubform[0].Page1[0].f1_41[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L29",
    "fieldName": "topmostSubform[0].Page1[0].f1_42[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L30_TotalSize",
    "fieldName": "topmostSubform[0].Page1[0].f1_43[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L30_WorkSize",
    "fieldName": "topmostSubform[0].Page1[0].f1_44[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L30",
    "fieldName": "topmostSubform[0].Page1[0].f1_45[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L31",
    "fieldName": "topmostSubform[0].Page1[0].f1_46[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C32a",
    "fieldName": "topmostSubform[0].Page1[0].c1_7[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "C32b",
    "fieldName": "topmostSubform[0].Page2[0].c2_1[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C33a",
    "fieldName": "topmostSubform[0].Page2[0].c2_2[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C34b",
    "fieldName": "topmostSubform[0].Page2[0].c2_3[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C34c",
    "fieldName": "topmostSubform[0].Page2[0].c2_4[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "L35",
    "fieldName": "topmostSubform[0].Page2[0].f2_1[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L36",
    "fieldName": "topmostSubform[0].Page2[0].f2_2[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L37",
    "fieldName": "topmostSubform[0].Page2[0].f2_3[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L38",
    "fieldName": "topmostSubform[0].Page2[0].f2_4[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L39",
    "fieldName": "topmostSubform[0].Page2[0].f2_5[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L40",
    "fieldName": "topmostSubform[0].Page2[0].f2_6[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L41",
    "fieldName": "topmostSubform[0].Page2[0].f2_7[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L42",
    "fieldName": "topmostSubform[0].Page2[0].f2_8[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L43_MM",
    "fieldName": "topmostSubform[0].Page2[0].f2_9[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L43_DD",
    "fieldName": "topmostSubform[0].Page2[0].f2_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L43_YY",
    "fieldName": "topmostSubform[0].Page2[0].f2_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L44a",
    "fieldName": "topmostSubform[0].Page2[0].f2_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L44b",
    "fieldName": "topmostSubform[0].Page2[0].f2_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L44c",
    "fieldName": "topmostSubform[0].Page2[0].f2_14[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L45_NO",
    "fieldName": "topmostSubform[0].Page2[0].c2_5[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "L46_NO",
    "fieldName": "topmostSubform[0].Page2[0].c2_6[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "L47a_NO",
    "fieldName": "topmostSubform[0].Page2[0].c2_7[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "L47b_NO",
    "fieldName": "topmostSubform[0].Page2[0].c2_8[1]",
    "fieldType": "Boolean",
    "checkmark": "No"
  },
  {
    "nickname": "L48_Expense1",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item1[0].f2_15[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48_Amount1",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item1[0].f2_16[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48_Expense2",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item2[0].f2_17[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48_Amount2",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item2[0].f2_18[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48_Expense3",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item3[0].f2_19[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48_Amount3",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item3[0].f2_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48_Expense4",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item4[0].f2_21[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48_Amount4",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item4[0].f2_22[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48_Expense5",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item5[0].f2_23[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48_Amount5",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item5[0].f2_24[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48_Expense6",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item6[0].f2_25[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48_Amount6",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item6[0].f2_26[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48_Expense7",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item7[0].f2_27[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48_Amount7",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item7[0].f2_28[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48_Expense8",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item8[0].f2_29[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48_Amount8",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item8[0].f2_30[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48_Expense9",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item9[0].f2_31[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48_Amount9",
    "fieldName": "topmostSubform[0].Page2[0].PartVTable[0].Item9[0].f2_32[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L48",
    "fieldName": "topmostSubform[0].Page2[0].f2_33[0]",
    "fieldType": "String"
  },
  {
    "nickname": "c1_1_0",
    "fieldName": "topmostSubform[0].Page1[0].c1_1[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "c1_1_1",
    "fieldName": "topmostSubform[0].Page1[0].c1_1[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "c1_2_0",
    "fieldName": "topmostSubform[0].Page1[0].c1_2[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  },
  {
    "nickname": "c1_4_0",
    "fieldName": "topmostSubform[0].Page1[0].c1_4[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  },
  {
    "nickname": "c1_5_0",
    "fieldName": "topmostSubform[0].Page1[0].c1_5[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  },
  {
    "nickname": "c1_7_0",
    "fieldName": "topmostSubform[0].Page1[0].c1_7[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "c2_4_0",
    "fieldName": "topmostSubform[0].Page2[0].c2_4[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  },
  {
    "nickname": "c2_5_0",
    "fieldName": "topmostSubform[0].Page2[0].c2_5[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  },
  {
    "nickname": "c2_6_0",
    "fieldName": "topmostSubform[0].Page2[0].c2_6[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  },
  {
    "nickname": "c2_7_0",
    "fieldName": "topmostSubform[0].Page2[0].c2_7[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  },
  {
    "nickname": "c2_8_0",
    "fieldName": "topmostSubform[0].Page2[0].c2_8[0]",
    "fieldType": "Boolean",
    "checkmark": "Off"
  }
];
