// This file was automatically generated by taxes/src/mappings/builder.ts

export interface F1040 {
  Single?: boolean;
  MarriedJoint?: boolean;
  MarriedSeparate?: boolean;
  HeadOfHousehold?: boolean;
  Widow?: boolean;
  StatusInfo?: string;
  FirstNameMI?: string;
  LastName?: string;
  SSN?: string;
  SpouseFirstNameMI?: string;
  SpouseLastName?: string;
  SpouseSSN?: string;
  StreetAddress?: string;
  Apt?: string;
  City?: string;
  State?: string;
  Zip?: string;
  ForeignCountry?: string;
  ForeignState?: string;
  ForeignZip?: string;
  PresidentialWweFund?: boolean;
  PresidentialWweFundSpouse?: boolean;
  HasCrypto_Yes?: boolean;
  HasCrypto_No?: boolean;
  Dependent?: boolean;
  SpouseDependent?: boolean;
  SpouseSeparate?: boolean;
  IsOld?: boolean;
  IsBlind?: boolean;
  HasOldSpouse?: boolean;
  HasBlindSpouse?: boolean;
  MoreThanFourDependnts?: boolean;
  D1_Name?: string;
  D1_SSN?: string;
  D1_Rel?: string;
  C0_D1_IsChildTaxCredit?: boolean;
  C0_D1_IsOtherDependent?: boolean;
  D2_Name?: string;
  D2_SSN?: string;
  D2_Rel?: string;
  C25?: boolean;
  C0_D2_IsOtherDependent?: boolean;
  D3_Name?: string;
  D3_SSN?: string;
  D3_Rel?: string;
  C0_D3_IsChildTaxCredit?: boolean;
  C0_D3_IsOtherDependent?: boolean;
  D4_Name?: string;
  D4_SSN?: string;
  D4_Rel?: string;
  C0_D4_IsChildTaxCredit?: boolean;
  C0_D4_IsOtherDependent?: boolean;
  L1?: string;
  L2a?: string;
  L2b?: string;
  L3a?: string;
  L3b?: string;
  L4a?: string;
  L4b?: string;
  L5a?: string;
  L5b?: string;
  L6a?: string;
  L6b?: string;
  HasCapGains?: boolean;
  L7?: string;
  L8?: string;
  L9?: string;
  L10a?: string;
  L10b?: string;
  L10c?: string;
  L11?: string;
  L12?: string;
  L13?: string;
  L14?: string;
  L15?: string;
  L16_0?: boolean;
  L16_1?: boolean;
  L16_2?: boolean;
  L16_3?: string;
  L16?: string;
  L17?: string;
  L18?: string;
  L19?: string;
  L20?: string;
  L21?: string;
  L22?: string;
  L23?: string;
  L24?: string;
  L25a?: string;
  L25b?: string;
  L25c?: string;
  L25d?: string;
  L26?: string;
  L27?: string;
  L28?: string;
  L29?: string;
  L30?: string;
  L31?: string;
  L32?: string;
  L33?: string;
  L34?: string;
  C35a?: boolean;
  L35a?: string;
  L35b?: string;
  C35b?: boolean;
  IsChecking?: boolean;
  L35d?: string;
  L36?: string;
  L37?: string;
  L38?: string;
  C35c?: boolean;
  DesignateThirdParty?: boolean;
  ThirdPartyName?: string;
  ThirdPartyPhone?: string;
  ThirdPartyPin?: string;
  Occupation?: string;
  PIN?: string;
  SpouseOccupation?: string;
  SpousePIN?: string;
  PhoneNumber?: string;
  Email?: string;
  PreparerName?: string;
  PreparerPTIN?: string;
  SelfEmployed?: boolean;
  PreparerFirm?: string;
  PreparerPhone?: string;
  PreparerAddress?: string;
  PreparerEIN?: string;
}

export const f1040 = [
  {
    "nickname": "Single",
    "fieldName": "topmostSubform[0].Page1[0].FilingStatus[0].c1_01[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "MarriedJoint",
    "fieldName": "topmostSubform[0].Page1[0].FilingStatus[0].c1_01[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "MarriedSeparate",
    "fieldName": "topmostSubform[0].Page1[0].FilingStatus[0].c1_01[2]",
    "fieldType": "Boolean",
    "checkmark": "3"
  },
  {
    "nickname": "HeadOfHousehold",
    "fieldName": "topmostSubform[0].Page1[0].FilingStatus[0].c1_01[3]",
    "fieldType": "Boolean",
    "checkmark": "4"
  },
  {
    "nickname": "Widow",
    "fieldName": "topmostSubform[0].Page1[0].FilingStatus[0].c1_01[4]",
    "fieldType": "Boolean",
    "checkmark": "5"
  },
  {
    "nickname": "StatusInfo",
    "fieldName": "topmostSubform[0].Page1[0].FilingStatus[0].f1_01[0]",
    "fieldType": "String"
  },
  {
    "nickname": "FirstNameMI",
    "fieldName": "topmostSubform[0].Page1[0].f1_02[0]",
    "fieldType": "String"
  },
  {
    "nickname": "LastName",
    "fieldName": "topmostSubform[0].Page1[0].f1_03[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SSN",
    "fieldName": "topmostSubform[0].Page1[0].YourSocial[0].f1_04[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SpouseFirstNameMI",
    "fieldName": "topmostSubform[0].Page1[0].f1_05[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SpouseLastName",
    "fieldName": "topmostSubform[0].Page1[0].f1_06[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SpouseSSN",
    "fieldName": "topmostSubform[0].Page1[0].SpousesSocial[0].f1_07[0]",
    "fieldType": "String"
  },
  {
    "nickname": "StreetAddress",
    "fieldName": "topmostSubform[0].Page1[0].Address[0].f1_08[0]",
    "fieldType": "String"
  },
  {
    "nickname": "Apt",
    "fieldName": "topmostSubform[0].Page1[0].Address[0].f1_09[0]",
    "fieldType": "String"
  },
  {
    "nickname": "City",
    "fieldName": "topmostSubform[0].Page1[0].Address[0].f1_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "State",
    "fieldName": "topmostSubform[0].Page1[0].Address[0].f1_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "Zip",
    "fieldName": "topmostSubform[0].Page1[0].Address[0].f1_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "ForeignCountry",
    "fieldName": "topmostSubform[0].Page1[0].Address[0].f1_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "ForeignState",
    "fieldName": "topmostSubform[0].Page1[0].Address[0].f1_14[0]",
    "fieldType": "String"
  },
  {
    "nickname": "ForeignZip",
    "fieldName": "topmostSubform[0].Page1[0].Address[0].f1_15[0]",
    "fieldType": "String"
  },
  {
    "nickname": "PresidentialWweFund",
    "fieldName": "topmostSubform[0].Page1[0].c1_02[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "PresidentialWweFundSpouse",
    "fieldName": "topmostSubform[0].Page1[0].c1_03[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "HasCrypto_Yes",
    "fieldName": "topmostSubform[0].Page1[0].c1_04[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "HasCrypto_No",
    "fieldName": "topmostSubform[0].Page1[0].c1_04[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "Dependent",
    "fieldName": "topmostSubform[0].Page1[0].c1_05[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "SpouseDependent",
    "fieldName": "topmostSubform[0].Page1[0].c1_06[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "SpouseSeparate",
    "fieldName": "topmostSubform[0].Page1[0].c1_07[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "IsOld",
    "fieldName": "topmostSubform[0].Page1[0].c1_08[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "IsBlind",
    "fieldName": "topmostSubform[0].Page1[0].c1_09[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "HasOldSpouse",
    "fieldName": "topmostSubform[0].Page1[0].c1_10[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "HasBlindSpouse",
    "fieldName": "topmostSubform[0].Page1[0].c1_11[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "MoreThanFourDependnts",
    "fieldName": "topmostSubform[0].Page1[0].Dependents_ReadOrder[0].c1_12[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C0_D1_IsChildTaxCredit",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow1[0].c1_13[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C0_D1_IsOtherDependent",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow1[0].c1_14[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C0_D2_IsOtherDependent",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow2[0].c1_16[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C0_D3_IsChildTaxCredit",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow3[0].c1_17[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C0_D3_IsOtherDependent",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow3[0].c1_18[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C0_D4_IsChildTaxCredit",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow4[0].c1_19[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C0_D4_IsOtherDependent",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow4[0].c1_20[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "D1_Name",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow1[0].f1_16[0]",
    "fieldType": "String"
  },
  {
    "nickname": "D1_SSN",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow1[0].f1_17[0]",
    "fieldType": "String"
  },
  {
    "nickname": "D1_Rel",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow1[0].f1_18[0]",
    "fieldType": "String"
  },
  {
    "nickname": "D2_Name",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow2[0].f1_19[0]",
    "fieldType": "String"
  },
  {
    "nickname": "D2_SSN",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow2[0].f1_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "D2_Rel",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow2[0].f1_21[0]",
    "fieldType": "String"
  },
  {
    "nickname": "D3_Name",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow3[0].f1_22[0]",
    "fieldType": "String"
  },
  {
    "nickname": "D3_SSN",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow3[0].f1_23[0]",
    "fieldType": "String"
  },
  {
    "nickname": "D3_Rel",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow3[0].f1_24[0]",
    "fieldType": "String"
  },
  {
    "nickname": "D4_Name",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow4[0].f1_25[0]",
    "fieldType": "String"
  },
  {
    "nickname": "D4_SSN",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow4[0].f1_26[0]",
    "fieldType": "String"
  },
  {
    "nickname": "D4_Rel",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow4[0].f1_27[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_28[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L2a",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_29[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L2b",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_30[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L3a",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_31[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L3b",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_32[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L4a",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_33[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L4b",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_34[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5a",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_35[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5b",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_36[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L6a",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_37[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L6b",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_38[0]",
    "fieldType": "String"
  },
  {
    "nickname": "HasCapGains",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].c1_21[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L7",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_39[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_40[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L9",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_41[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L10a",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].Line10-12_ReadOrder[0].f1_42[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L10b",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].Line10-12_ReadOrder[0].f1_43[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L10c",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_44[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L11",
    "fieldName": "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_45[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L12",
    "fieldName": "topmostSubform[0].Page1[0].f1_46[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L13",
    "fieldName": "topmostSubform[0].Page1[0].f1_47[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14",
    "fieldName": "topmostSubform[0].Page1[0].f1_48[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L15",
    "fieldName": "topmostSubform[0].Page1[0].f1_49[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L16_0",
    "fieldName": "topmostSubform[0].Page2[0].c2_01[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L16_1",
    "fieldName": "topmostSubform[0].Page2[0].c2_02[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L16_2",
    "fieldName": "topmostSubform[0].Page2[0].c2_03[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L16_3",
    "fieldName": "topmostSubform[0].Page2[0].f2_01[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L16",
    "fieldName": "topmostSubform[0].Page2[0].f2_02[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L17",
    "fieldName": "topmostSubform[0].Page2[0].f2_03[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L18",
    "fieldName": "topmostSubform[0].Page2[0].f2_04[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L19",
    "fieldName": "topmostSubform[0].Page2[0].f2_05[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L20",
    "fieldName": "topmostSubform[0].Page2[0].f2_06[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L21",
    "fieldName": "topmostSubform[0].Page2[0].f2_07[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L22",
    "fieldName": "topmostSubform[0].Page2[0].f2_08[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L23",
    "fieldName": "topmostSubform[0].Page2[0].f2_09[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L24",
    "fieldName": "topmostSubform[0].Page2[0].f2_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L25a",
    "fieldName": "topmostSubform[0].Page2[0].Line25_ReadOrder[0].f2_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L25b",
    "fieldName": "topmostSubform[0].Page2[0].Line25_ReadOrder[0].f2_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L25c",
    "fieldName": "topmostSubform[0].Page2[0].Line25_ReadOrder[0].f2_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L25d",
    "fieldName": "topmostSubform[0].Page2[0].Lines26-27_ReadOrder[0].f2_14[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L26",
    "fieldName": "topmostSubform[0].Page2[0].Lines26-27_ReadOrder[0].f2_15[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C25",
    "fieldName": "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow2[0].c1_15[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L27",
    "fieldName": "topmostSubform[0].Page2[0].Lines27-32_ReadOrder[0].f2_16[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L28",
    "fieldName": "topmostSubform[0].Page2[0].Lines27-32_ReadOrder[0].f2_17[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L29",
    "fieldName": "topmostSubform[0].Page2[0].Lines27-32_ReadOrder[0].f2_18[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L30",
    "fieldName": "topmostSubform[0].Page2[0].Lines27-32_ReadOrder[0].f2_19[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L31",
    "fieldName": "topmostSubform[0].Page2[0].Lines27-32_ReadOrder[0].f2_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L32",
    "fieldName": "topmostSubform[0].Page2[0].Line32-33_ReadOrder[0].f2_21[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L33",
    "fieldName": "topmostSubform[0].Page2[0].f2_22[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L34",
    "fieldName": "topmostSubform[0].Page2[0].f2_23[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C35a",
    "fieldName": "topmostSubform[0].Page2[0].c2_04[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C35b",
    "fieldName": "topmostSubform[0].Page2[0].c2_05[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "C35c",
    "fieldName": "topmostSubform[0].Page2[0].c2_6[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L35a",
    "fieldName": "topmostSubform[0].Page2[0].f2_24[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L35b",
    "fieldName": "topmostSubform[0].Page2[0].RoutingNo[0].f2_25[0]",
    "fieldType": "String"
  },
  {
    "nickname": "IsChecking",
    "fieldName": "topmostSubform[0].Page2[0].c2_05[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "L35d",
    "fieldName": "topmostSubform[0].Page2[0].AccountNo[0].f2_26[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L36",
    "fieldName": "topmostSubform[0].Page2[0].f2_27[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L37",
    "fieldName": "topmostSubform[0].Page2[0].f2_28[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L38",
    "fieldName": "topmostSubform[0].Page2[0].f2_32[0]",
    "fieldType": "String"
  },
  {
    "nickname": "DesignateThirdParty",
    "fieldName": "topmostSubform[0].Page2[0].c2_6[1]",
    "fieldType": "Boolean",
    "checkmark": "2"
  },
  {
    "nickname": "ThirdPartyName",
    "fieldName": "topmostSubform[0].Page2[0].f2_33[0]",
    "fieldType": "String"
  },
  {
    "nickname": "ThirdPartyPhone",
    "fieldName": "topmostSubform[0].Page2[0].f2_34[0]",
    "fieldType": "String"
  },
  {
    "nickname": "ThirdPartyPin",
    "fieldName": "topmostSubform[0].Page2[0].f2_35[0]",
    "fieldType": "String"
  },
  {
    "nickname": "Occupation",
    "fieldName": "topmostSubform[0].Page2[0].f2_36[0]",
    "fieldType": "String"
  },
  {
    "nickname": "PIN",
    "fieldName": "topmostSubform[0].Page2[0].f2_37[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SpouseOccupation",
    "fieldName": "topmostSubform[0].Page2[0].f2_38[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SpousePIN",
    "fieldName": "topmostSubform[0].Page2[0].f2_39[0]",
    "fieldType": "String"
  },
  {
    "nickname": "PhoneNumber",
    "fieldName": "topmostSubform[0].Page2[0].f2_40[0]",
    "fieldType": "String"
  },
  {
    "nickname": "Email",
    "fieldName": "topmostSubform[0].Page2[0].f2_41[0]",
    "fieldType": "String"
  },
  {
    "nickname": "PreparerName",
    "fieldName": "topmostSubform[0].Page2[0].f2_42[0]",
    "fieldType": "String"
  },
  {
    "nickname": "PreparerPTIN",
    "fieldName": "topmostSubform[0].Page2[0].f2_43[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SelfEmployed",
    "fieldName": "topmostSubform[0].Page2[0].c2_07[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "PreparerFirm",
    "fieldName": "topmostSubform[0].Page2[0].f2_44[0]",
    "fieldType": "String"
  },
  {
    "nickname": "PreparerPhone",
    "fieldName": "topmostSubform[0].Page2[0].f2_45[0]",
    "fieldType": "String"
  },
  {
    "nickname": "PreparerAddress",
    "fieldName": "topmostSubform[0].Page2[0].f2_46[0]",
    "fieldType": "String"
  },
  {
    "nickname": "PreparerEIN",
    "fieldName": "topmostSubform[0].Page2[0].f2_47[0]",
    "fieldType": "String"
  }
];
