/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface F1040Sa {
  f1_1_0?: string;
  f1_2_0?: string;
  f1_3_0?: string;
  f1_4_0?: string;
  f1_5_0?: string;
  f1_6_0?: string;
  c1_1_0?: boolean;
  f1_7_0?: string;
  f1_8_0?: string;
  f1_9_0?: string;
  f1_10_0?: string;
  f1_11_0?: string;
  f1_12_0?: string;
  f1_13_0?: string;
  f1_14_0?: string;
  f1_15_0?: string;
  c1_2_0?: boolean;
  f1_16_0?: string;
  f1_17_0?: string;
  f1_18_0?: string;
  f1_19_0?: string;
  f1_20_0?: string;
  f1_21_0?: string;
  f1_22_0?: string;
  f1_23_0?: string;
  f1_24_0?: string;
  f1_25_0?: string;
  f1_26_0?: string;
  f1_27_0?: string;
  f1_28_0?: string;
  f1_29_0?: string;
  f1_30_0?: string;
  f1_31_0?: string;
  f1_32_0?: string;
  f1_33_0?: string;
  f1_34_0?: string;
  c1_3_0?: boolean;
}


export const f1040sa = [
  {
    "nickname": "Name",
    "fieldName": "topmostSubform[0].Page1[0].f1_1[0]",
    "fieldType": "String"
  },
  {
    "nickname": "SSN",
    "fieldName": "topmostSubform[0].Page1[0].f1_2[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L1",
    "fieldName": "topmostSubform[0].Page1[0].f1_3[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L2",
    "fieldName": "topmostSubform[0].Page1[0].f1_4[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L3",
    "fieldName": "topmostSubform[0].Page1[0].f1_5[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L4",
    "fieldName": "topmostSubform[0].Page1[0].f1_6[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C5a",
    "fieldName": "topmostSubform[0].Page1[0].c1_1[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L5a",
    "fieldName": "topmostSubform[0].Page1[0].f1_7[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5b",
    "fieldName": "topmostSubform[0].Page1[0].f1_8[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5c",
    "fieldName": "topmostSubform[0].Page1[0].f1_9[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5d",
    "fieldName": "topmostSubform[0].Page1[0].f1_10[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L5e",
    "fieldName": "topmostSubform[0].Page1[0].f1_11[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L6_Etc1",
    "fieldName": "topmostSubform[0].Page1[0].f1_12[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L6_Etc2",
    "fieldName": "topmostSubform[0].Page1[0].f1_13[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L6",
    "fieldName": "topmostSubform[0].Page1[0].f1_14[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L7",
    "fieldName": "topmostSubform[0].Page1[0].f1_15[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C8a",
    "fieldName": "topmostSubform[0].Page1[0].Line8_ReadOrder[0].c1_2[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  },
  {
    "nickname": "L8a",
    "fieldName": "topmostSubform[0].Page1[0].f1_16[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8b_Etc1",
    "fieldName": "topmostSubform[0].Page1[0].f1_17[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8b_Etc2",
    "fieldName": "topmostSubform[0].Page1[0].f1_18[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8b",
    "fieldName": "topmostSubform[0].Page1[0].f1_19[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8c",
    "fieldName": "topmostSubform[0].Page1[0].f1_20[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8d",
    "fieldName": "topmostSubform[0].Page1[0].f1_21[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L8e",
    "fieldName": "topmostSubform[0].Page1[0].f1_22[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L9",
    "fieldName": "topmostSubform[0].Page1[0].f1_23[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L10",
    "fieldName": "topmostSubform[0].Page1[0].f1_24[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L11",
    "fieldName": "topmostSubform[0].Page1[0].f1_25[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L12",
    "fieldName": "topmostSubform[0].Page1[0].f1_26[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L13",
    "fieldName": "topmostSubform[0].Page1[0].f1_27[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L14",
    "fieldName": "topmostSubform[0].Page1[0].f1_28[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L15",
    "fieldName": "topmostSubform[0].Page1[0].f1_29[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L16_Etc1",
    "fieldName": "topmostSubform[0].Page1[0].f1_30[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L16_Etc2",
    "fieldName": "topmostSubform[0].Page1[0].f1_31[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L16_Etc3",
    "fieldName": "topmostSubform[0].Page1[0].f1_32[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L16",
    "fieldName": "topmostSubform[0].Page1[0].f1_33[0]",
    "fieldType": "String"
  },
  {
    "nickname": "L17",
    "fieldName": "topmostSubform[0].Page1[0].f1_34[0]",
    "fieldType": "String"
  },
  {
    "nickname": "C18",
    "fieldName": "topmostSubform[0].Page1[0].Line18_ReadOrder[0].c1_3[0]",
    "fieldType": "Boolean",
    "checkmark": "1"
  }
];
