const Apps = {
  Token: "Token",
} as const;

const Methods = {
  Approval: "Approval",
  Transfer: "Transfer",
} as const;

const Tokens = {
  _1INCH: "_1INCH",
  _3Crv: "_3Crv",
  ADT: "ADT",
  ankrCRV: "ankrCRV",
  aRAI: "aRAI",
  BAL: "BAL",
  BAT: "BAT",
  BUSD: "BUSD",
  CHERRY: "CHERRY",
  CRV: "CRV",
  crvPlain3andSUSD: "crvPlain3andSUSD",
  DAI: "DAI",
  dusd3CRV: "dusd3CRV",
  ENJ: "ENJ",
  eursCRV: "eursCRV",
  GEN: "GEN",
  GNO: "GNO",
  GRT: "GRT",
  GTC: "GTC",
  gusd3CRV: "gusd3CRV",
  GUSD: "GUSD",
  hCRV: "hCRV",
  HEGIC: "HEGIC",
  husd3CRV: "husd3CRV",
  KNC: "KNC",
  LINK: "LINK",
  linkCRV: "linkCRV",
  MANA: "MANA",
  MATIC: "MATIC",
  MKR: "MKR",
  musd3CRV: "musd3CRV",
  OMG: "OMG",
  PETH: "PETH",
  RAI: "RAI",
  REN: "REN",
  RENFIL: "RENFIL",
  REP: "REP",
  REPv2: "REPv2",
  SAI: "SAI",
  SNT: "SNT",
  SNX: "SNX",
  SPANK: "SPANK",
  stkAAVE: "stkAAVE",
  sUSD: "sUSD",
  sUSDT: "sUSDT",
  TORN: "TORN",
  TUSD: "TUSD",
  USDC: "USDC",
  usdn3CRV: "usdn3CRV",
  usdp3CRV: "usdp3CRV",
  usdt3CRV: "usdt3CRV",
  USDT: "USDT",
  ust3CRV: "ust3CRV",
  WBTC: "WBTC",
  WETH: "WETH",
  WMATIC: "WMATIC",
  XSUSHI: "XSUSHI",
  yDAI_yUSDC_yUSDT_yBUSD: "yDAI_yUSDC_yUSDT_yBUSD",
  yDAI_yUSDC_yUSDT_yTUSD: "yDAI_yUSDC_yUSDT_yTUSD",
  ZRX: "ZRX",
} as const;

export const enums = { Apps, Methods, Tokens };
